### ISSUE TITLE
create a calendar item inviting people

### ISSUE THREAD

**Issue by erickengelke** [Garethp/php-ews#10]
I see how to create a calendar item for myself, but I need to also invite other people.  How do I do that with this framework?

**Comment by Garethp** [comment]
Hi. Do you mean inviting them to a preexisting event or inviting them when you create the event?

**Comment by erickengelke** [comment]
Inviting them when I create the event.

**Comment by Garethp** [comment]
Try something like this

```php
use jamesiarmes\PEWS\API;

$api = API::withUsernameAndPassword('server', 'username', 'password');
$calendar = $api->getCalendar();

$start = new DateTime('8:00 AM');
$end = new DateTime('9:00 AM');

$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Persons Name',
                'EmailAddress' => 'Persons Email Address'
            )
        )
    )
));
```

I just added a RequiredAttendees data to the createCalendarItem example

**Comment by erickengelke** [comment]
thanks, I will try that

**Comment by Garethp** [comment]
Did this work for you?

**Comment by Garethp** [comment]
Hey @erickengelke, can you let me know how this went for you?

**Comment by Garethp** [comment]
I'm closing this from non-response. If you still have an issue, let me know

**Comment by erickengelke** [comment]
Sorry, I was away for a few weeks.

I have not been able to figure out how to use your libraries.  This namespace and use is new to me, and hours later I still haven't figured it out.  You must have other lines or command line switches or something to somehow indicate these files are used.  But I don't see any examples that work for me.  I'm using PHP 5.6.16

**Comment by Garethp** [comment]
Hi Erik, do you know how to use Composer? Have you installed this through Composer?

**Comment by erickengelke** [comment]
No, I didn't know about Composer - I take it that is the missing piece.  I
just downloaded the libs/examples through GitHup.  I will look into
Composer right now.

**Comment by erickengelke** [comment]
Okay, I install and run composer.  It adds the following
-rw-r--r--   1 root   erick  62624 Mar  9 09:28 composer.lock
-rwxr--r--   1 erick  erick    939 Mar  8 12:47 phpunit.live.xml
-rwxr--r--   1 erick  erick    941 Mar  8 12:47 phpunit.record.xml
drwxr-xr-x  17 root   erick    512 Mar  9 09:28 vendor

But I still don't understand how to run the examples without getting

PHP Fatal error:  Class 'jamesiarmes\PEWS\API' not found in
/usr/home/erick/ews/jamesiarmes/jamesiarmes/PEWS/examples/calendar/createItem.php
on line 5

**Comment by erickengelke** [comment]
your instructions say "composer require garethp/php-ews
so I do:
 php ../../composer.phar require garethp/php-ews
Using version ^0.7.4 for garethp/php-ews
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package garethp/php-ews No version set (parsed as
1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to
your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for
more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further
common problems.

Installation failed, reverting ./composer.json to its original content.
root@dark:/home/erick/ews/jamesiarmes/PEWS #

**Comment by Garethp** [comment]
What does your composer.json look like?

**Comment by Garethp** [comment]
This is what happened when I tried to composer require my package in a new directory

```
composer require garethp/php-ews
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^0.7.4 for garethp/php-ews
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzlehttp/promises (1.1.0)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.2.3)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.1.1)
    Loading from cache

  - Installing garethp/php-ews (v0.7.4)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

**Comment by erickengelke** [comment]
I've downloaded it fresh to a new subdirectory:
using the composer.json that you distribute unchanged

$ php ../../composer.phar require garethp/php-ews
Using version ^0.7.4 for garethp/php-ews
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package garethp/php-ews No version set (parsed as
1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to
your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for
more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further
common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by erickengelke** [comment]
I've replicated your environment, but I get stuck where I show above.  Does
it have to be in some specific subdirectory?

**Comment by erickengelke** [comment]
Okay, I've figured out how to install.

My json is

{
    "require": {
        "garethp/php-ews": "dev-master"
    }
}

How do I run a php program with it?

**Comment by Garethp** [comment]
Change it to 

```json
{
    "require": {
        "garethp/php-ews": "^0.7.4"
    }
}
```

Then delete your `composer.lock` file and try running `composer install`

**Comment by erickengelke** [comment]
Okay, got it to run!!!!

It adds to my calendar, but not to the other person's... which is my final
goal.


<?php

require_once __DIR__.'/vendor/autoload.php';

use jamesiarmes\PEWS\API;

$api = API::withUsernameAndPassword('connect.uwaterloo.ca', 'engcompc',
'BlahBlahBlah');
$calendar = $api->getCalendar();

$start = new DateTime('8:01 AM');
$end = new DateTime('9:00 AM');

$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Erick Engelke',
                'EmailAddress' => 'erick@uwaterloo.ca'
            )
        )
    )
));
?>

Erick

**Comment by Garethp** [comment]
Yes, you need to add him as a attendee as well as yourself

```php
$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Erick Engelke',
                'EmailAddress' => 'erick@uwaterloo.ca'
            )
        ),
        array(
            'Mailbox' => array(
                'Name' => 'The Other Person',
                'EmailAddress' => 'Their Email Address'
            )
        )
    )
));
```

That should be about right

**Comment by erickengelke** [comment]
I'm logging in as engcompc, which will be my calendar robot account, and
trying to add Erick, which is the other person.  T

he event does get scheduled for engcompc successfully, but not for Erick,
who is the other person. Also, no Email is sent, might that be the problem?

I've tried adding RoutingType='SMTP', and a variety of other things, but it
never sends a message to Erick.

BTW, using OutlookWebConnect, I verified that engcompc is privileged enough
to create a tentative calendar event for Erick, so that's  not my problem.

Erick

**Comment by Garethp** [comment]
If you want to send an email out, you need to add that as an option when creating. Like this

```php
$calendar->createCalendarItems($stuff, array(
    'SendMeetingInvitations' => 'SendOnlyToAll'
));
```

Try that, let me know how it goes

**Comment by erickengelke** [comment]
No luck, it never sends the Email.  I looked at the returned variable with
print_r, there is no error message.

Erick

**Comment by erickengelke** [comment]
To recap, I've got
<?php

require_once __DIR__.'/vendor/autoload.php';

use jamesiarmes\PEWS\API;

$api = API::withUsernameAndPassword('connect.uwaterloo.ca', 'engcompc',
'FoodBag0');
$calendar = $api->getCalendar();

$start = new DateTime('8:01 AM');
$end = new DateTime('9:00 AM');

$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'SendMeetingInvitations' => 'SendOnlyToAll',
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Erick Engelke',
                'EmailAddress' => 'erick@connect.uwaterloo.ca',
//                'RoutingType' => 'SMTP'
            ),
            'Mailbox' => array(
                'Name' => 'engcompc',
                'EmailAddress' => 'engcompc@uwaterloo.ca',
   //             'RoutingType' => 'SMTP'
            )
        )
    )
));
print_r( $createdItemIds );
?>

**Comment by erickengelke** [comment]
Wouldn't we want something more like:
...
$createdItemIds = $calendar->createCalendarItems(
$x = array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'SendMeetingInvitations' => 'SendToAllAndSaveCopy',
    'Location'=>'here',
    'RequiredAttendees' => array(
        'Attendee' => array(
            'Mailbox' => array(
                'Name' => 'Erick Engelke',
                'EmailAddress' => 'erick@uwaterloo.ca'
  //              'RoutingType' => 'SMTP'
            )
        )
    )
));
print_r( $x );
print_r( $createdItemIds );

Where we have 'Attendee'?  Of course, it still doesn't work.

$x  looks like
Array
(
    [Subject] => Test
    [Start] => 2016-03-10T08:01:00-05:00
    [End] => 2016-03-10T09:00:00-05:00
    [SendMeetingInvitations] => SendToAllAndSaveCopy
    [Location] => here
    [RequiredAttendees] => Array
        (
            [Attendee] => Array
                (
                    [Mailbox] => Array
                        (
                            [Name] => Erick Engelke
                            [EmailAddress] => erick@uwaterloo.ca
                        )

                )

        )

)

**Comment by erickengelke** [comment]
Note, it still doesn't send an Email to erick@uwaterloo.ca, even though
I've tried various options.

**Comment by erickengelke** [comment]
I'm Stil stuck.  Is there a way to see the SOAP message so I can debug that?

Erick

**Comment by Garethp** [comment]
I'm not sure why you're not getting an email, but I think I can see why your example to add multiple people didn't work. You did it like this

```php
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Erick Engelke',
                'EmailAddress' => 'erick@connect.uwaterloo.ca',
            ),
            'Mailbox' => array(
                'Name' => 'engcompc',
                'EmailAddress' => 'engcompc@uwaterloo.ca',
            )
        )
```

When you needed to do it like this

```php
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Erick Engelke',
                'EmailAddress' => 'erick@connect.uwaterloo.ca',
            ),
        ),
        array(
            'Mailbox' => array(
                'Name' => 'engcompc',
                'EmailAddress' => 'engcompc@uwaterloo.ca',
            )
        )
```

See, the difference is that you had both Mailbox keys in the same array. In PHP, you declare a key twice. They both need to be their own array. I ran a test myself, and this worked for me to add multiple people to an event

```php
$start = new DateTime('8:01 AM');
$end = new DateTime('9:00 AM');

$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'RequiredAttendees' => array(
        array(
            'Mailbox' => array(
                'Name' => 'Person 1',
                'EmailAddress' => 'first@email.com',
            )
        ),
        array (
            'Mailbox' => array(
                'Name' => 'Person 2',
                'EmailAddress' => 'second@email.com'
            )
        )
    )
), array('SendMeetingInvitations' => 'SendOnlyToAll'));
```

If you want to see the raw API response, you need to be using a debug environment capable of inserting break points in to your code. If you have that, you can put a break point in ExchangeWebServices.php on line 321 to see the response before it's processed

**Comment by erickengelke** [comment]
That works perfectly, THANKS!!!!!

Erick

**Comment by Garethp** [comment]
Also, from what I've gathered, recipients will receive emails but the person who created the event won't receive one

**Comment by erickengelke** [comment]
Good to know.
Erick
