### ISSUE TITLE
Error trying to create appointment

### ISSUE THREAD

**Issue by Geoffry304** [Garethp/php-ews#100]
Hello,

I am getting next error when trying to use the example of creating an appointment.
The request failed schema validation: The element 'Items' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages' has incomplete content. List of possible elements expected: 'Item, Message, CalendarItem, Contact, DistributionList, MeetingMessage, MeetingRequest, MeetingResponse, MeetingCancellation, Task, PostItem, ReplyToItem, ForwardItem, ReplyAllToItem, AcceptItem, TentativelyAcceptItem, DeclineItem, CancelCalendarItem, RemoveItem, SuppressReadReceipt, PostReplyItem, AcceptSharingInvitation' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.

I am using the latest version, but on an other application i am using version 0.6.* and here I still can add appointments.

What can the problem be? 

Regards Geoffry

**Comment by feldmarv** [comment]
We encounter the same problem since several weeks. Before it was working with same code.

**Comment by feldmarv** [comment]
Downgrading the version to "garethp/php-ews": "0.9.2", fixed the problem on our side.

**Comment by Garethp** [comment]
Sorry for the late reply. I just pushed out version `0.9.4` which should fix the issue. Can you please try that?

**Comment by Geoffry304** [comment]
0.9.4 fixes the problem, thank you!

**Comment by Garethp** [comment]
I'm sorry for taking so long with the fix. Thanks for giving it a shot :)
