### ISSUE TITLE
An internal server error occurred. The operation failed.

### ISSUE THREAD

**Issue by sirio3mil** [Garethp/php-ews#101]
After update from 0.9.2 to 0.9.3, I'm getting this error when I send email through an Exchange 2013 SP1. I can list inbox mail, the error is when I try to send anything.

**Comment by Garethp** [comment]
Hi. Sorry for the late response, but I just release Version `0.9.4`. This should hopefully fix your issue. Can you try again?

**Comment by sirio3mil** [comment]
Ok I'll try and give you feedback

**Comment by sirio3mil** [comment]
I can't find version 0.9.4 with composer

**Comment by Garethp** [comment]
What does your `composer.json` file look look like? If it looks like 

```json
{
    "require": {
        "garethp/php-ews": "^0.9.3"
    }
}
```

Then a simple `composer update garethp/php-ews` should install it.

**Comment by sirio3mil** [comment]
It works
