### ISSUE TITLE
1000 entries limit?

### ISSUE THREAD

**Issue by mvangoor** [Garethp/php-ews#104]
Hi,

I have been struggling with this for quite some time now and probably just need a pointer or something.

I have a mailbox I am trying to read that holds 50000+ items and I would like to be able to iterate all of them. How do I achieve that since all I seem to be getting is a maximum of 1000 items.

Thanks for any pointers!

Regards,
Mike

**Comment by mvangoor** [comment]
An update, I (finally) found that a single findItem can at any given time return a maximum of 1000 entries.
I did read something about paging or multiple queries, is any of that possible?

**Comment by biroplane** [comment]
Did you find out?

**Comment by mvangoor** [comment]
Hi biroplane,

Yes I did, it is a limitation which cannot be changed in Microsoft Exchange.
Since then I have been using the timestamp (+1) of the last message I received to get the next load.

Regards,
mike

**Comment by Garethp** [comment]
@mvangoor @biroplane Sorry for the belated response. There is actually a better method of pagination that's in my examples folder. Perhaps I should re-arrange the examples folder for people to go through it more easily. [Here's an example of how you page through contacts](https://github.com/Garethp/php-ews/blob/master/examples/basic/pagingRequests.php), it should be the same for doing it for an inbox
