### ISSUE TITLE
List All Public folders

### ISSUE THREAD

**Issue by biroplane** [Garethp/php-ews#108]
I'm searching a method to list all my (company / shared) contact folders.
I need to list all contacts (6,5k contacts) that are in a folder (outside main contacts folder) named "Other Contacts" -> "Total Contacts" 

i can't figure out how to get the id of that particular folder, or list all the public folders where i have access.

Thank you in advance

**Comment by Garethp** [comment]
Hi.

Have you tried something along the lines of `$this->getFolderByDisplayName('My Public Folder', Enumeration\DistinguishedFolderIdNameType::PUBLICFOLDERSROOT);`? In [this example](https://github.com/Garethp/php-ews/blob/master/examples/calendar/workingWithPublicCalendars.php), it's how I get a public folder for calendars. Maybe it'll work for contacts as well?

**Comment by biroplane** [comment]
I'll Try! thanks!
