### ISSUE TITLE
set 'MaxEntriesReturned' to display all contacts

### ISSUE THREAD

**Issue by biroplane** [Garethp/php-ews#109]
Hi again!
i'm trying to display all my contacts in the public folder (Thanks @Garethp for your advises!) but even if i set MaxEntriesReturned to 9999 it displays only the first 1000 contacts (i know that they must be 6500)
do i need to iterate singularly each contact and move the 'offset' parameter? It looks memory-expensive for a large amount of contacts...
here's my code..

```
$api = MailAPI::withUsernameAndPassword($host, $username, $password);
        $apiContacts = API::withUsernameAndPassword($host, $username, $password);
        $folder1 = $apiContacts->getFolderByDisplayName('Public Folders', Enumeration\DistinguishedFolderIdNameType::PUBLICFOLDERSROOT);
        $subFolder3 = $apiContacts->getFolderByDisplayName('totalContacts', $folder1->getFolderId());
        $apiContacts->setFolderId($subFolder3->getFolderId());
        $contacts = $apiContacts->getContacts($subFolder3->getFolderId(),[
            'IndexedPageItemView' => [
                'MaxEntriesReturned' => 9999,
                'Offset' => 0,
                'BasePoint' => 'Beginning'
            ]
        ]);
        
        $i=0;
        foreach($contacts->getItems() as $contact){
            print "<pre><h4>CONTATTO $i</h4>";
            print_r($contact);
            print "<br />--------------------------------------------</pre>";
            $i++;
        }
```

**Comment by fury118** [comment]
Hi

did you find a way to get all your contacts ?

**Comment by Garethp** [comment]
Hi. It turns out that the maximum amount of items returned by EWS is 1000 items. I have an exmple [`on how to paginate through results`](https://github.com/Garethp/php-ews/blob/master/examples/basic/pagingRequests.php)
