### ISSUE TITLE
Working period / Get user availablity request

### ISSUE THREAD

**Issue by pjwj** [Garethp/php-ews#11]
I am trying to get working period (days) for a specific account. The only method I found which returns it is GetUserAvailability. I tried to building a request from an array for that. However error message says:
'Property ResponseMessages does not exist' (Line 64 in MagicMethodsTrait.php). Printing out the response before the exception gets thrown showed that xml response is correct.
As I was looking for a solution I found [here](https://msdn.microsoft.com/en-us/library/office/hh532567%28v=exchg.80%29.aspx) that the xml response for GetUerAvailability method does not contain "ResponseMessages" (other xml responses do).

Any suggestions to fix this?

Here is how I built the request from an array:
```
$request = new GetUserAvailabilityRequestType();

$request = array(
    "TimeZone" => array(
        "Bias" => '480',
        "StandardTime" => array(
            "Bias" => 0,
            "Time" => '02:00:00',
            "DayOrder" => 5,
            "Month" => 10,
            "DayOfWeek" => "Sunday"
        ),
        "DaylightTime" => array(
            "Bias" => 0,
            "Time" => '02:00:00',
            "DayOrder" => 1,
            "Month" => 4,
            "DayOfWeek" => "Sunday"
        )
    ),
    "MailboxDataArray" => array(
        "MailboxData" => array(
            "Email"=> array(
                "Address" => $requestor_email
            ),
            "AttendeeType" => 'Required',
            "ExcludeConflicts" => false
        )
    ),
    "FreeBusyViewOptions" => array(
        "TimeWindow" => array(
            "StartTime" => $start,
            "EndTime" => $end
        ),
        "MergedFreBusyIntervalInMinutes" => 30,
        "RequestedView" => 'DetailedMerged'
    )
);

$request = Type::buildFromArray($request);
$response = $api->getClient()->GetUserAvailability($request);

var_dump($response);
```

**Comment by Garethp** [comment]
Now that... is interesting. I didn't know that there were some responses that didn't contain a ResponseMessages property. What happens is that `ExchangeWebServices` has a function that "Drills Down Responses". What this means is that it tries to go through the unneeded levels of response items to return only the pertinent information. So when you do a `GetItem` request, you don't need to do a `$response->getResponseMessages()->getItemResponseMessage()->getItems()->getMessage()` kind of thing. However, this drilling down assumes that all responses have a ResponseMessage property. I'll take a look at this to try and fix it. In the mean time, if you want to have a workaround while I fix this you can pass in an option when creating the API to bypass the drilling down. Like this

```php
$api = API::withUsernameAndPassword($server, $username, $password, array(
    'drillDownResponses' => false
));
```

**Comment by Garethp** [comment]
Hey, so I've pushed a quick fix for your issue tagged as version `0.7.3`, can you give it a test and let me know if it works? The fix just checks whether or not the property `ResponseMessages` exists on the message. If it doesn't, it just returns the full response to you (In your case it'll return a `GetUserAvailabilityResponseType` class) instead of drilling down

**Comment by pjwj** [comment]
The fix works for me, Cheers! Great support!

**Comment by Garethp** [comment]
At some point I'll add support to do this operation more easily like other functions, but for now I'm going to close this ticket. Check back in a week or two for an easier way to do it

**Comment by Garethp** [comment]
Hi pjwj. I tried to simplify the request some more, but was unable to actually achieve it. [This issue](https://github.com/Garethp/php-ews/issues/13) explains what I tried if you want to take a look. In the end I could think of a set of API calls simple enough to cut out most of the code, but flexible enough to be useful to lots of people.
