### ISSUE TITLE
How To Get Calendar Body

### ISSUE THREAD

**Issue by robp2175** [Garethp/php-ews#110]
I know that I have to make a separate request to get the calendar body, but not sure how to go about doing that. Could someone point me in the right direction. I appreciate it.

**Comment by Garethp** [comment]
Here you go

```php
$items = $calendar->getCalendarItems();
foreach ($items as $item) {
    $item = $calendar->getCalendarItem($item->getItemId()->getId(), $item->getItemId()->getChangeKey());
    $body = (string) $item->getBody();
}
```

**Comment by robp2175** [comment]
Thank you so much, worked perfectly of course.
