### ISSUE TITLE
Is is possible to delete a calendar itme with just the ID Number

### ISSUE THREAD

**Issue by robp2175** [Garethp/php-ews#111]
I would like to be able to delete a calendar item using just the ID number, for example, like below. Ofcourse, $calendar->deleteCalendarItem(); will delete a single calendar item using the ItemID, but not the ID number. What would be the most elegant way to accomplish this. Thank you for any assistance.

AAMkADhhMWE1YTBiLTNjMzUtNDRiOS1hNzVjLWU3OGYxNjE1MjRkNQBGAAAAAABTlO/Ki8zMT6NjAWqCFjPwBwDOciiyHR+PT643JCSa61tXAAAAPiSLAAA9rDYfe3LYTbQdvBbbSHgQAANXFsiKAAA=

**Comment by Garethp** [comment]
You'll probably need the ChangeKey as well (An ItemId is made of an Id and a ChangeKey), but you can do

```php
$calendar->deleteCalendarItem(new ItemIdType($id, $changeKey));
```

**Comment by miranwarwtc** [comment]
> You'll probably need the ChangeKey as well (An ItemId is made of an Id and a ChangeKey), but you can do
> 
> ```
> $calendar->deleteCalendarItem(new ItemIdType($id, $changeKey));
> ```

Trying to do this exactly ($calendar->deleteCalendarItem(new ItemIdType($id, $changeKey));) but for some reason  it's not wanting to delete the calendar item. Wondering if something changed with this library. 

Thank you!
