### ISSUE TITLE
Oh my god how do this works

### ISSUE THREAD

**Issue by PrieurBenjamin** [Garethp/php-ews#113]
Hi !

Im very sorry to do this, but i have to.
Im in need of a EWS API in PHP, that will allow me to access my Exchange Server and take all the mails in it that correspond to another email adresse (send, received.).

But i don't understand at all.

The tutorial say : 
The library can be used to make several different request types. In order to make a request, you need to instantiate a new API object:

$ews = API::fromUsernameAndPassword($server, $username, $password, $options = array());

Where the f*** do i need to put it ?!?

I've already done the installation with composer, but the following is... I don't understand at all.

Please. Help me.

I thank you all for reading this.

Biohazard

**Comment by Garethp** [comment]
Have you taken a look at my [`examples`](https://github.com/Garethp/php-ews/tree/master/examples) folder? It holds good starting points for how to do many things. One that might help, is that [this is an example of how to get items in the inbox](https://github.com/Garethp/php-ews/blob/master/examples/mail/listItems.php). But that won't give you your whole solution. You'll likely need to [paginate your request](https://github.com/Garethp/php-ews/blob/master/examples/basic/pagingRequests.php) if you have more items than you get back in one response, you may have to [specify a different folder than your inbox](https://github.com/Garethp/php-ews/blob/master/src/MailAPI.php#L41), which is done pretty similarly to [how you would get items from a different folder in your calendar](https://github.com/Garethp/php-ews/blob/master/examples/calendar/workingWithDifferentCalendars.php) and for getting sent items you may need to [get the folder ID of the sent folder, and set that directly](https://github.com/Garethp/php-ews/blob/master/examples/calendar/workingWithPublicCalendars.php).

That being said, I'm not sure exactly what you're after. Once you've read the examples, if you still have any questions, feel free to try and explain what you're after and what problems you have.

**Comment by PrieurBenjamin** [comment]
Oh my.

Thanks A LOT Garethp. Haven't just though you will respond to to this in person and that fast. Thanks you.
I apologies for this incomprehension, thank you again. I get to the Exemples folder, get into the find.php, and put all the connection information.
But now, when launching it with WAMP, it say this

`Fatal error: Uncaught RuntimeException: Curl error: SSL certificate problem: self signed certificate in C:\wamp\www\PHPExchange\php-ews-master\vendor\jamesiarmes\php-ntlm\src\SoapClient.php:91 Stack trace: #0 [internal function]: jamesiarmes\PhpNtlm\SoapClient->__doRequest('<?xml version="...', 'https://reserva...', 'http://schemas....', 1, 0) #1 C:\wamp\www\PHPExchange\php-ews-master\src\Client.php(1631): SoapClient->__call('FindItem', Array) #2 C:\wamp\www\PHPExchange\php-ews-master\src\Client.php(670): jamesiarmes\PhpEws\Client->makeRequest('FindItem', Object(jamesiarmes\PhpEws\Request\FindItemType)) #3 C:\wamp\www\PHPExchange\php-ews-master\examples\message\find.php(73): jamesiarmes\PhpEws\Client->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType)) #4 {main} thrown in C:\wamp\www\PHPExchange\php-ews-master\vendor\jamesiarmes\php-ntlm\src\SoapClient.php on line 91`

Can you help me again ?

Ben

**Comment by Garethp** [comment]
Well, first of all it looks like you're using a different library to mine. It looks like you're using [`jamesiarmes/php-ews`](https://github.com/jamesiarmes/php-ews). 

Secondly, it looks like you're mail server is using a self-signed SSL certificate, which it shouldn't be

**Comment by PrieurBenjamin** [comment]
Okay.

Downloaded Your library, got the autoload.php with composer.

I don't want to be anoying anymore, but do you know how to change the certificate ? Otherwise, which one taking ?

Thank you,

Ben

**Comment by Garethp** [comment]
No, sorry. That's something you need to sort out with your server administrator

**Comment by PrieurBenjamin** [comment]
Thank you.

We have our Exchange server hosted at OVH.
We are going to send a mail saying we must change the certificate. DO you know the name of the certificate we need ?

**Comment by Garethp** [comment]
You just need a signed SSL certificate
