### ISSUE TITLE
Handle Push notifications

### ISSUE THREAD

**Issue by ajefferiss** [Garethp/php-ews#114]
At the moment I'm using `SubscribeType` and `PushSubscriptionRequestType` to get notifications of new messages appearing in my inbox sent over to a notification script I'm attempting to write, a version of https://github.com/jamesiarmes/php-ews/issues/280 but using your fork. I'm however running into errors with the `SoapServer` and what I presume is the WSDL. My most basic script (far from complete I know) is shown below, but it produces an error:  

> Fatal error:  Procedure 'SendNotification' not present in log.php on line 18

```
<?php

require_once('vendor/autoload.php');

class EwsPushService
{
    public function SendNotification($arg)
    {
        file_put_contents('debug', print_r($arg, true));
    }
}

$server = new SoapServer(
    'vendor/garethp/php-ews/Resources/wsdl/services.wsdl',
    array('uri' => 'http://mydomain.com/log.php')
);
$server->setObject($service = new EwsPushService());
$server->handle();
```

Do you have any suggestions on what I need to do to handle push notifications?

**Comment by Garethp** [comment]
Well, the issue you're running in to here is that you need to reference the `NotificationService.wsdl` wsdl, not the `services.wsdl`. `garethp/php-ews` doesn't come with the `NotificationService.wsdl` file, and netiher does `jamesiarmes/php-ews`, so you'll have to download and include one yourself. A quick google search shows a file [here](https://github.com/mulesoft-consulting/connect4retail/blob/master/src/main/resources/service/NotificationService.wsdl), but I don't know if it's out of date or not. Try that, let me know how it goes

**Comment by ajefferiss** [comment]
Ah ok, misunderstood what WSDL was being used but that's done it.

Thanks for the help.
