### ISSUE TITLE
Cancel a Meeting

### ISSUE THREAD

**Issue by Shaeldon** [Garethp/php-ews#115]
Hello,

is there a way to cancel a meeting? Currently I just remove the Calendar entry which was fine since the other attendee was a room which auto-canceled when the Item got removed but now I'm starting to add real persons.

I only found the declineMeeting() method which doesnt work, since i cant decline my own meeting and I actually want to cancel it, not decline it.

Any suggestions?

Thanks,
Shaeldon

**Comment by nathanpond** [comment]
Mine sends out cancellation notices:

```
$options = array(
        'SendMeetingCancellations' => Enumeration\CalendarItemCreateOrDeleteOperationType::SEND_ONLY_TO_ALL
    );
    $item_id = new Type\ItemIdType($cal_item_id, $cal_change_key);
    $calendar->deleteCalendarItem($item_id, $options);
```

Is that what you need?

**Comment by Shaeldon** [comment]
Exactly what i was looking for.
Thank you very much!
