### ISSUE TITLE
Update Calendar and send update email

### ISSUE THREAD

**Issue by nathanpond** [Garethp/php-ews#116]
If I'm reading the code correctly, it appears to me that there's no way to set the SendMeetingInvitationsOrCancellations option in updateCalendarItem().  Th function doesn't accept an $options parameter like the create and delete functions do.  And then the updateCalendarItem function hard codes SendMeetingInvitationsOrCancellations to 'SendToNone'.

Am I missing something obvious?  I almost created a PR to handle options similar to the other functions but felt like I was missing something simple.

**Comment by Garethp** [comment]
Good catch, thanks. This was just an oversight, it wasn't left intentionally like that. Version `0.9.6` now comes with an `$options` parameter for `CalendarAPI::updateCalendarItem`
