### ISSUE TITLE
SOAP Error object have no SubscriptionStatus property

### ISSUE THREAD

**Issue by ajefferiss** [Garethp/php-ews#117]
I've been attempting to get Push Subscriptions and Notifications to work; however the notification handler that I had put together kept getting an error: 

> PHP Fatal error:  SOAP-ERROR: Encoding: object has no 'SubscriptionStatus' property in 

The handler itself, in the most basic form:
```
<?php

ini_set("soap.wsdl_cache_enabled", 0);
require_once('vendor/autoload.php');

use garethp\ews\API;
use garethp\ews\API\ExchangeWebServicesAuth;
use garethp\ews\API\Type\ConnectingSIDType;
use garethp\ews\API\Type\ExchangeImpersonation;
use garethp\ews\API\Type\ItemIdType;
use garethp\ews\API\Type\NonEmptyArrayOfBaseItemIdsType;
use garethp\ews\API\Type\ItemResponseShapeType;
use garethp\ews\API\Message\SendNotificationResultType;
use garethp\ews\API\Message\SendNotificationResult;
use garethp\ews\API\Message\ArrayOfResponseMessagesType;
use garethp\ews\API\Message\SendNotificationResponseType;
use garethp\ews\API\Message\GetItemType;
use garethp\ews\API\Enumeration\DefaultShapeNamesType;
use garethp\ews\API\Enumeration\SubscriptionStatusType;

class EwsPushService
{
    public function SendNotification($arg)
    {
        $responseCode = $arg->ResponseMessages->SendNotificationResponseMessage->ResponseCode;
        if ($responseCode == "NoError") {
            $notification = $arg->ResponseMessages->SendNotificationResponseMessage->Notification;
            if (isset($notification->NewMailEvent)) {
                // Download message
            }
        }

        $notificationResponse = new SendNotificationResultType();
        $notificationResponse->setSubscriptionStatus(SubscriptionStatusType::OK);

        return $notificationResponse;
    }
}

$service = new EwsPushService();
$server = new SoapServer('php-ews/wsdl/NotificationService.wsdl');
$server->setObject($service);
$server->handle();
```

This appears to be an issue with the `SendNotificationResultType` class, looking at the [messages.xsd](https://github.com/lafar6502/nginn-exchange/blob/master/ExchangeIntegration.Service/EWS/messages.xsd) file; the element within the type is `SubscriptionStatus` while the [library](https://github.com/Garethp/php-ews/blob/master/src/API/Message/SendNotificationResultType.php) uses `subscriptionStatus`, jamesiarmes uses [SubscriptionStatus](https://github.com/jamesiarmes/php-ews/blob/master/src/Type/SendNotificationResultType.php). So I believe it's a simple mismatch between the XSD and implementation.

```
<xs:complexType name="SendNotificationResultType">
    <xs:sequence>
      <xs:element name="SubscriptionStatus" type="t:SubscriptionStatusType" />
    </xs:sequence>
</xs:complexType>
```

I'm testing the changes at the moment, but wanted to raise the issue incase what I've found is wrong and I've missed something obivious...

**Comment by Garethp** [comment]
Yeah, I wanted to comply with PSR-2 code style, so my objects have lower case property names. Before it gets sent to SOAP, this gets turned to uppercase. Try `return $notificationResponse->toXmlObject()`. If you look at `->toXmlObject()`, it has a `ucfirst` on the property names. Normally this happens automatically when you make a request, but in this case you're going about it in a different manner so you'll need to call it manually

**Comment by ajefferiss** [comment]
Thanks, when you say I'm going about it in a different manner is there someway you'd recommend doing this instead?

**Comment by Garethp** [comment]
Not really. I've never approached this before. I built this library to be a **client** to Soap, not to act as a Soap Server. But once you've got this working, I'll find a neat way to add this to the library in an easy to use way.

**Comment by ajefferiss** [comment]
Ok, thanks again for your help. Changing to `return $notificationResponse->toXmlObject()` worked correctly.

**Comment by Garethp** [comment]
When you've got your complete working solution, can you post it as an issue to this repo, and I'll make a release around it
