### ISSUE TITLE
getTotalCount on public folder

### ISSUE THREAD

**Issue by tarreislam** [Garethp/php-ews#119]
Hello.

I am trying to use the `getTotalCount` on a public folder on our 2k10SE setup, but the value is always null. 

```PHP
    $CustomersFolder = $client->getFolderByDisplayName('AAA', DistinguishedFolderIdNameType::PUBLICFOLDERSROOT);
    $test = $client->getFolderByDisplayName('BBB', $CustomersFolder->getFolderId());
    dd($test->getTotalCount()); // NULL
```

I do not think its a problem with the php-ews package, but could the fact that we run everything in SWEDISH has to do with anything? 

Thanks in advance

**Comment by Garethp** [comment]
Not really. It looks like it has more to do with the options being sent to Exchange during the request. [`getFolderByDisplayName`](https://github.com/Garethp/php-ews/blob/master/src/API.php#L364) essentially calls [`getChildrenFolders`](https://github.com/Garethp/php-ews/blob/master/src/API.php#L334), which creates a [`FindFolder`](https://msdn.microsoft.com/en-us/library/office/aa563918(v=exchg.150).aspx) request against Exchange. When we make the request, we make it with the following options

```php
$request = array(
    'Traversal' => 'Shallow',
    'FolderShape' => array(
        'BaseShape' => 'AllProperties'
    ),
    'ParentFolderIds' => array(
        'FolderId' => $parentFolderId->toArray()
    )
);
```

On the documentation for the [`FindFolder`](https://msdn.microsoft.com/en-us/library/office/aa563918(v=exchg.150).aspx) operation, under comments, there's this strange note:

> FindFolder responses to a request with the AllProperties response shape will not return the TotalCount and UnreadCount elements for public folder searches.

Why does `AllProperties` not return all properties? Who knows. Still, we can see from the documentation that using `Default` as the `BaseShape` will in fact return a totalCount. And in `php-ews`, you can easily override the default options. Try this and let me know if it works:

```php
$test = $client->getFolderByDisplayName('BBB', $CustomersFolder->getFolderId(), array (
    'FolderShape' => array('BaseShape' => 'Default')
));
```

I think that *should* work, but I haven't tried it

**Comment by tarreislam** [comment]
Hi again.

Thanks for the quick answer. But it gave me the same result.


I Came across [`this stackoverflow answer`](https://stackoverflow.com/a/24747016) which gave me an idea. And what do you know, it worked.

Its a detour but ill take it just to get it to work!

```PHP
$CustomersFolder = $client->getFolderByDisplayName('AAA', DistinguishedFolderIdNameType::PUBLICFOLDERSROOT);

$test = $client->getFolderByDisplayName('BBB', $CustomersFolder->getFolderId());

dd($client->getFolderByFolderId($test->getFolderId()->getId())); // shows count and unread count
```

**Comment by Garethp** [comment]
Glad to hear you found the answer! Sorry I couldn't be more helpful. Let me know if you have any other issues

**Comment by tarreislam** [comment]
Thank you!
