### ISSUE TITLE
Get an item by its id

### ISSUE THREAD

**Issue by Robinouh** [Garethp/php-ews#121]
Hi,

I am currently trying to get an item (email) by its id.

I imagine a function that would look like this:

```
public function getMail($id)
{
    $itemId = $api->getItemByItemId($id)->getItemId();

    $mail = $api->getMailItems(null,
    [
        'Restriction' => [
            'IsEqualTo' => [
                'FieldURI' => [
                    'FieldURI' => Enumeration\UnindexedFieldURIType::ITEM_ID
                ],
                    'FieldURIOrConstant' => [
                        'Constant' => [
                        'Value' => $itemId
                    ]
                ]
            ]
        ]
    ]);

    return $mail;
}
```

Obviously, the function "getItemByItemId" does not exist but there is maybe a function to do that?

**Comment by Shaeldon** [comment]
Hello Robinouh,
the function in question is called "getItem"

If $mailid is just the ID-String and not the object:
`$mail = $api->getItem(new API\Type\ItemIdType($mailid));`

**Comment by Robinouh** [comment]
Hi Shaeldon,

Thank you very much for your quick response, it works perfectly!
