### ISSUE TITLE
Get list of all available folders?

### ISSUE THREAD

**Issue by Shaeldon** [Garethp/php-ews#125]
Hello there,

Is there a way to get a list of all available folders? Email/Contacts?

I know how to get specific ones I know of, but what to do if I don't know the names?

Update:

While doing this:
```
$Api = ContactsAPI::withUsernameAndPassword($this->server, $this->username, $this->password, ['impersonation' => $user['email']]);

            $test = $Api->getChildrenFolders();
            foreach ($test as $stuff){
                var_dump($stuff->getDisplayName());
            }
```
I get this result:
string(19) "BrokerSubscriptions"
string(21) "CalendarItemSnapshots"
string(30) "CalendarSharingCacheCollection"
string(12) "Common Views"
string(27) "DefaultFoldersChangeHistory"
string(15) "Deferred Action"
string(16) "ExchangeSyncData"
string(19) "FileCollectionCache"
string(6) "Finder"
string(18) "Folder Memberships"
string(13) "Freebusy Data"
string(10) "GraphStore"
string(9) "Inference"
string(8) "Location"
string(19) "MailboxAssociations"
string(18) "MailboxMoveHistory"
string(13) "MeetingSapces"
string(24) "O365 Suite Notifications"
string(18) "O365 Suite Storage"
string(12) "OneDriveRoot"
string(4) "PACE"
string(14) "ParkedMessages"
string(27) "Pass-Through Search Results"
string(10) "PdpProfile"
string(12) "PdpProfileV2"
string(13) "PeopleConnect"
string(14) "PeopleInsights"
string(17) "Recoverable Items"
string(8) "Schedule"
string(20) "ShardRelevancyFolder"
string(23) "SharePointNotifications"
string(7) "Sharing"
string(9) "Shortcuts"
string(15) "SmsAndChatsSync"
string(13) "Subscriptions"
string(6) "System"
string(15) "TeamChatHistory"
string(14) "TemporarySaves"
string(24) "Top of Information Store"
string(31) "UserSocialActivityNotifications"
string(5) "Views"
string(32) "XrmActivityClientInstrumentation"
string(32) "XrmActivityServerInstrumentation"
string(17) "XrmActivityStream"
string(15) "XrmDeletedItems"
string(11) "XrmInsights"
string(11) "XrmProjects"
string(14) "Contact Search"
string(11) "AllContacts"
string(8) "AllItems"
string(17) "AllPersonMetadata"
string(8) "Bekannte"
string(22) "Calendar Version Store"
string(30) "Document Centric Conversations"
string(12) "Erinnerungen"
string(9) "Favorites"
string(14) "Meine Kontakte"
string(18) "MyContactsExtended"
string(33) "Nachverfolgte E-Mail-Verarbeitung"
string(13) "People I Know"
string(16) "RelevantContacts"
string(13) "Spooler Queue"
string(12) "To-Do Search"
string(23) "XrmActivityStreamSearch"
string(16) "XrmCompanySearch"
string(13) "XrmDealSearch"
string(9) "XrmSearch"
string(11) "Orion Notes"

I dont think i am inside the contacts folder.

When trying to do `$Api->getFolderByDisplayName('contacts');` I only get false back.

How do i enter the "basic" contacts folder?

Thanks a lot!

**Comment by Garethp** [comment]
Sorry for the late reply. You do it by adding the ID of the parent folder to `getChildrenFolders`, like this

```php
$api->getChildrenFolders(\garethp\ews\API\Enumeration\DistinguishedFolderIdNameType::CONTACTS);
```
