### ISSUE TITLE
Get Organizer info?

### ISSUE THREAD

**Issue by jbostoen** [Garethp/php-ews#127]
I'm working on a project and discovered this fork of php-ews.
Seems a lot has changed and been simplified.

One thing I'm running into:
How do I obtain the organizer info of a calendar item? (Display name, email address) ?

Use case: listing events from a meeting room, I want to provide details on the organizer.

**Comment by Garethp** [comment]
Hi

Have you tried using the `->getOrganiziser()` method? Does it not have what you want?

Example:

```php
$item = $api->getCalendarItem('', '');
$name = $item->getOrganizer()->getMailbox()->getName();
$emailAddress = $item->getOrganizer()->getMailbox()->getEmailAddress();
```

While a lot of things have been simplified, it's only simplifying how you actually get the objects from Exchange. Once you've got them, they're kept in the same structure as the XML, or the same structure as the original project

**Comment by jbostoen** [comment]
Thanks, works like a charm!
