### ISSUE TITLE
Example of ResolveNames?

### ISSUE THREAD

**Issue by jbostoen** [Garethp/php-ews#128]
Would it be possible to provide an example on how to resolve names?

From the calendar, I get something like this as "EmailAddress": "O=REDACTED/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=USERNAME"

I'd like to resolve this to my name and SMTP address.

I tried something like this, but it fails.
```

			$requestMailBoxInfo = new ResolveNamesType();
			$requestMailBoxInfo->setUnresolvedEntry("O=GEMEENTEIZEGEM/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=JBOSTOEN" ); # $params["EmailAddress"]; # Could be something like  o=GemeenteIzegem/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=jbostoen if running as jbostoen 
			$requestMailBoxInfo->setReturnFullContactData( false ); # would show a lot more 
			
 
			
			$requestMailBoxInfo = $this->client->ResolveNames( $requestMailBoxInfo );		
```

What would be the proper way to obtain the (display) name and email address? Thanks!

**Comment by Garethp** [comment]
When it fails, what's the error? Have you seen something like this in an example somewhere else before? If you're familiar with Exchange Web Services, are you able to find an article in the EWS Soap Documentation where this is documented with XML request and response?

**Comment by jbostoen** [comment]
- I was trying to get the equivalent of https://github.com/jamesiarmes/php-ews/issues/338 
- Is this what you meant for documentation? https://msdn.microsoft.com/en-us/library/aa493895(v=exchg.80).aspx

**Comment by jbostoen** [comment]
Is this something which should be possible with your library? Or is there an alternative to turn "O=REDACTED/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=USERNAME" into  a regular mail address and display name?

Thanks!

**Comment by Garethp** [comment]
Hi

Sorry for the late reply. Can you try something like:

```php
$api = API::withUsernameAndPassword($serverUri, $username, $password);

$request = [
    'UnresolvedEntry' => 'O=REDACTED/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=USERNAME',
    'ReturnFullContactData' => false
];
$response = $api->getClient()->ResolveNames($request);

var_dump($response);
```
And tell me what you get?

**Comment by jbostoen** [comment]
Thanks for the exampe. It works if I set an email address for unresolved entry. But it failed when attempting to set O=REDACTED-OU/OU=EXCHANGE ADMINISTRATIVE GROUP (REDACTED-ID)/CN=RECIPIENTS/CN=SOMEUSERNAME

However, the solution is quite easy. I compared it with the ticket in the original library. It needs an extra slash before O=REDACTED in your example.

```
$api = API::withUsernameAndPassword($serverUri, $username, $password);

$request = [
    'UnresolvedEntry' => '**/**O=REDACTED/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=USERNAME',
    'ReturnFullContactData' => false
];
$response = $api->getClient()->ResolveNames($request);

var_dump($response);
```

May I suggest adding this as an example (with email address - SMTP and Exchange format)?

Keep up the great work!

**Comment by Garethp** [comment]
Will do. If there's any other requests that you want to use, but don't know how, take a look at how the XML request is in the EWS documentation, and then just build an array that looks like that. All my library does is take the array and pass it in to the SOAP library. The extra functions just make it so that for the most common use cases (that I'm aware of), you don't need to know the structure. But for anything that I haven't covered, the XML in the documentation *should* show you how to build the request. I'll copy the XML I mean just so that you know what I'm talking about:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ResolveNames xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                  ReturnFullContactData="true">
      <UnresolvedEntry xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">Test</UnresolvedEntry>
</ResolveNames>
```

```php
$request = [
    'UnresolvedEntry' => '/O=REDACTED/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=USERNAME',
    'ReturnFullContactData' => false
];
$response = $api->getClient()->ResolveNames($request);
```

It's basically that simple for all requests. I'll add this as an example, and I hope that this was helpful to you
