### ISSUE TITLE
Make a simple method for getting a users availability request

### ISSUE THREAD

**Issue by Garethp** [Garethp/php-ews#13]
## User Availability Request

Currently this is the best way to get availability. There's more information on the raw calls found [here](https://msdn.microsoft.com/en-us/library/office/dn643673(v=exchg.150).aspx). It includes a lot of timezone data, something I've been trying to avoid due to the difference between EWS timezones and PHP timezones, as well as recurrences in the header. The implementation of headers at the moment could really use some beefing up. Looking at the `NTLMSoapClient` implementation, I remove a certain header temporarily for DeleteItem and SyncFolderItems requests by a hardcoded index in the default headers. This is because you can't pass timezone data for those calls for some reason. Frankly looking at it, it should break if you're using Timezones, Impersonation and Version headers all at the same time. So that needs fixing up. The actual response doesn't look too bad, but finding a good way of crafting the request will be interesting...

```php
$request = new GetUserAvailabilityRequestType();

$request = array(
    "TimeZone" => array(
        "Bias" => '480',
        "StandardTime" => array(
            "Bias" => 0,
            "Time" => '02:00:00',
            "DayOrder" => 5,
            "Month" => 10,
            "DayOfWeek" => "Sunday"
        ),
        "DaylightTime" => array(
            "Bias" => 0,
            "Time" => '02:00:00',
            "DayOrder" => 1,
            "Month" => 4,
            "DayOfWeek" => "Sunday"
        )
    ),
    "MailboxDataArray" => array(
        "MailboxData" => array(
            "Email"=> array(
                "Address" => $requestor_email
            ),
            "AttendeeType" => 'Required',
            "ExcludeConflicts" => false
        )
    ),
    "FreeBusyViewOptions" => array(
        "TimeWindow" => array(
            "StartTime" => $start,
            "EndTime" => $end
        ),
        "MergedFreBusyIntervalInMinutes" => 30,
        "RequestedView" => 'DetailedMerged'
    )
);

$request = Type::buildFromArray($request);
$response = $api->getClient()->GetUserAvailability($request);

var_dump($response);
```

**Comment by Garethp** [comment]
One issue is now solved: Headers in `NTLMSoapClient` are now smarter and no longer refer to hardcoded index's

**Comment by Garethp** [comment]
This doesn't appear to be something easily done at all. Unfortunately looking at the [Microsoft Documentation](https://msdn.microsoft.com/en-us/library/office/dn643673(v=exchg.150).aspx) for GetUserAvailability, there's so many options when making the request that I can't see an obvious solution to simplifying the process. I attempted to do this by allowing you to pass in variables to the `GetUserAvailabilityRequestType` constructor, but trying to take everything in to account turned in to basically the same level of complication any way, and I discovered that I could just use `buildFromArray` to do what I was already trying to do, as shown below

```php
$request = \jamesiarmes\PEWS\API\Message\GetUserAvailabilityRequest::buildFromArray(array(
    "MailboxDataArray" => array(
        "MailboxData" => array(
            "Email"=> array(
                "Address" => 'gareth@true.nl'
            ),
            "AttendeeType" => 'Required',
            "ExcludeConflicts" => false
        )
    ),
    "FreeBusyViewOptions" => array(
        "TimeWindow" => array(
            "StartTime" => (new DateTime('2016-02-24 11:00:00'))->format('c'),
            "EndTime" => (new DateTime('2016-02-24 15:00:00'))->format('c')
        ),
        "MergedFreBusyIntervalInMinutes" => 30,
        "RequestedView" => 'DetailedMerged'
    )
);
$response = $api->getClient()->GetUserAvailability($request);
```

So as it stands until I can think of a good, easy API call that's flexible enough to suit most purposes, this won't be simplified any time soon.

**Comment by synlol** [comment]
hello, Garethp
Why did I do as you wrote above? The request was invalid
