### ISSUE TITLE
Get Content of Single Mail

### ISSUE THREAD

**Issue by basementmedia2** [Garethp/php-ews#134]
Via the following code, i'm trying to get the content of a single Email:

```
require_once "vendor/autoload.php";
$email_id=$_POST["email_id"]; // Contains the Email_ID which i get via  $api->getItem($email->getItemId());

use garethp\ews\MailAPI;
use garethp\ews\API\Type;
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;

$api = MailAPI::withUsernameAndPassword("myserver", "myuser", "mypassword");

$inbox = $api->getFolderByDisplayName('Posteingang', DistinguishedFolderIdNameType::MESSAGE_ROOT);
$api->setFolderId($inbox->getFolderId());

$mail = $api->getItem(new API\Type\ItemIdType($email_id));

foreach ($mail as $email) {
	$subject = $email->getSubject();
        $body = (string) $email->getBody();
}
```

Unfortunately, i get the following error message:
"<b>Fatal error</b>:  Uncaught Error: Class 'API\Type\ItemIdType' not found in [...]"

But i got this file lying in directory "vendor/garethp/php-ews/src/API/Type"

Or is $mail = $api->getItem(new API\Type\ItemIdType($email_id)); not ok for getting a single mail?

I have also tried this
```
$mail = $api->getMailItems($subFolder1->getFolderId(), [
    'ItemIds' => [
        'ItemId' => $data['id'] // Or (new API\Type\ItemIdType($data['id']))
    ]
]);
```
which results in output of ALL mails of the mailbox.

Can anybody help me?
Also i want to delete a single mail?
Ist this also possible by email_id?

Best regards
Daniel

**Comment by Shaeldon** [comment]
Try adding this use statement:
`use garethp\ews\API;
`

**Comment by basementmedia2** [comment]
Now the fault message has changed:
```
$mail = $api->getItem(new API\Type\ItemIdType($email_id));
$subject = $email->getSubject();
$sender = $email->getSender()->getMailbox()->getEmailAddress();
$body = (string) $email->getBody();
$datum=$email->getDateTimeSent();
$datum=date("d.m.Y H:i:s", strtotime($datum)); 
```
Results now in : 
<b>Fatal error</b>:  Uncaught Error: Call to a member function getSubject() on null

When i use this code instead:
```
$mail = $api->getMailItems($inbox->getFolderId(),[
    'ItemIds' => [
        'ItemId' => new API\Type\ItemIdType($email_id) // Or (new API\Type\ItemIdType($data['id']))
    ]
]);
```
I get all Mails of the mailbox ;-(

Any further tips?

**Comment by basementmedia2** [comment]
Great! Now it works!
Is it possible to delete a single mail by ID?

**Comment by Shaeldon** [comment]
New error basicly just says that he could not find a mail.

I use the following code to retrieve a single mail:

`
$api->setFolderId($subFolder1->getFolderId());

$mail = $api->getItem(new API\Type\ItemIdType($data['id']));`

**Comment by basementmedia2** [comment]
Hi Shaeldon, 

while you wrote your answer, i deleted my last post.
Also the deleteItems works now.

Thanx a lot for your help!
