### ISSUE TITLE
Displaying inline-images

### ISSUE THREAD

**Issue by basementmedia2** [Garethp/php-ews#135]
Hi,

is it possible to display inline-images directly at the position within the email-body?
Actually if i display the body with
```
$body=(string) $mail->getBody();
```
the images are just representated by a "<img src="cid:something...">"

The former inline-image itself is contained in the attachmentArray which i get by
```
$fileAttachment_arr = $mail->getAttachments()->getFileAttachment();
if (count($fileAttachment_arr) >0) {
	foreach ($fileAttachment_arr as $att_item) {
		$attachment = $api->getAttachment($att_item->getAttachmentId());
		$att_name = $attachment->getName();
		$contentType = $attachment->getContentType();
		$att_content = $attachment->getContent();
	}
} 
```
Ist it possible maybe to get the CID from the $att_item object and then display the image inside the email body?

Best regards
Daniel

**Comment by Garethp** [comment]
Hi

I'm actually not sure about this. I haven't tried it before

**Comment by Garethp** [comment]
So this is how I managed to achieve this. You might want to test this with multiple different cases (Attaching files inline for example), since I just tried the first thing that works. I don't know how it'll react in different circumstances, but it should work. Or at least give you an idea of what to do.

```php
$mail = $api->getItem($itemId);
$body = (string) $mail->getBody();

foreach ($mail->getAttachments()->getFileAttachment() as $file) {
    /** @var $file \garethp\ews\API\Type\FileAttachmentType */
    if (!$file->isInline()) {
        continue;
    }

    $file = $api->getAttachment($file->getAttachmentId());

    $imageSrc = 'data:' . $file->getContentType() . ';base64,' . base64_encode((string) $file->getContent());
    $body = str_replace('src="cid:' . $file->getContentId() . '"', 'src="' . $imageSrc . '"', $body);
}
```

**Comment by basementmedia2** [comment]
Hi, perfect. Works for me!
