### ISSUE TITLE
Getting the email-signature

### ISSUE THREAD

**Issue by basementmedia2** [Garethp/php-ews#136]
Hi,

another day, another question:
Does the library provide a function for getting the personal email-signature which is saved for every user in our outlook exchange server?

Best regards
Daniel

**Comment by Garethp** [comment]
There's no pre-made method like there is for getting emails and attachments. However, if you find the EWS documentation for getting a signature, it's fairly easy to do anyway. You just need to know the structure of the request.

**Comment by basementmedia2** [comment]
OK, thanx, i will hopefully come back here with the solution.

**Comment by Garethp** [comment]
If you do find a piece of documentation on the Microsoft EWS website, #128 is an example of how you turn that in to usable code. If you take a look, it's basically a case of finding the an XML Request to do what you're after, then creating an Array that has the same structure.

**Comment by basementmedia2** [comment]
Hi,

this works for me now:

```
<?php
require_once "vendor/autoload.php";

use garethp\ews\API;
use garethp\ews\API\Message\GetUserConfigurationType;
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;
use garethp\ews\API\Enumeration\ResponseClassType;
use garethp\ews\API\Enumeration\UserConfigurationPropertyType;
use garethp\ews\API\Type\DistinguishedFolderIdType;
use garethp\ews\API\Type\UserConfigurationNameType;

$client = API::withUsernameAndPassword("myserver", "myuser", "mypassword");

$request = [
	'UserConfigurationName' => [
		'Name' => 'OWA.UserOptions',
		'DistinguishedFolderId' => ['Id' => DistinguishedFolderIdNameType::ROOT]
	],
	'UserConfigurationProperties' => UserConfigurationPropertyType::ALL
];

$response = $client->getClient()->GetUserConfiguration($request);
$uconfname=$response->getDictionary()->DictionaryEntry;
// In my case the Email-signatur is at array position 19. Maybe in other cases not
// But you can print_r($uconfname) to find it out ;-)
$signatur=$uconfname[19]->getDictionaryValue()->getValue();

echo $signatur;
?>

**Comment by Garethp** [comment]
Thank you for your example!
