### ISSUE TITLE
more than 1000 contacts

### ISSUE THREAD

**Issue by fury118** [Garethp/php-ews#139]
hi

i have 1988 contact in exchange

i tried this code:

```php
require_once 'vendor/autoload.php';

use garethp\ews\Contacts\ContactsAPI as API;
use \garethp\ews\API\Enumeration;

$api = API::withUsernameAndPassword($exchangeServeur, $exchangeUtilisateur, $exchangeMdp);
$firstPage = $api->getContacts(); 
echo $firstPage[0]->getGivenName()."-";
$secondPage = $api->getNextPage($firstPage); 
echo $secondPage[0]->getGivenName()."-";
```

if i use

```php
$api = API::withUsernameAndPassword($exchangeServeur, $exchangeUtilisateur, $exchangeMdp, ['drillDownResponses' => false]);
```

i get

```
Fatal error: Uncaught Exception: Property FolderId does not exist in C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php:118 

Stack trace: #0 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(54): garethp\ews\API\Type->getValidNameInCorrectCase(Array) 
#1 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(28): garethp\ews\API\Type->get('FolderId') 
#2 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\ContactsAPI.php(44): garethp\ews\API\Type->__call('getFolderId', Array) 
#3 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\ContactsAPI.php(66): garethp\ews\ContactsAPI->getFolderId() 
#4 C:\xampp\htdocs\secure\ajax\intervenantAnnuaireSync.php(58): garethp\ews\ContactsAPI->getContacts()
#5 {main} thrown in C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php on line 118
```

and i got two time the same name.
Did i do Something wrong ?

regards

**Comment by Garethp** [comment]
Sorry, can you please update your version to `dev-master` and just see if this issue is still on there?

**Comment by fury118** [comment]
hi

i just copy your garethp php-ews-master.zip on my code
i didn't change http-playback, guzzlehttp, psr

My code:

require_once 'vendor/autoload.php';
use garethp\ews\Contacts\ContactsAPI as API;
use \garethp\ews\API\Enumeration;
$api = API::withUsernameAndPassword($exchangeServeur, $exchangeUtilisateur, $exchangeMdp, ['drillDownResponses' => false]);

$firstPage = $api->getContacts(); 

foreach ($firstPage as $contacts) 
{ 
	print_r($contacts)."-";		
} 

$secondPage = $api->getNextPage($firstPage); 

result:

the foreach ($firstPage as $contacts) shows nothing


Fatal error: Uncaught Exception: Property IsIncludesLastItemInRange does not exist in C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php:118 Stack trace: #0 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(89): garethp\ews\API\Type->getValidNameInCorrectCase(Array) #1 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(28): garethp\ews\API\Type->is('IncludesLastIte...') #2 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API.php(474): garethp\ews\API\Type->__call('isIncludesLastI...', Array) #3 C:\xampp\htdocs\secure\ajax\intervenantAnnuaireSync.php(76): garethp\ews\API->getNextPage(Object(garethp\ews\API\Message\FindItemResponseType)) #4 {main} thrown in C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php on line 118

**Comment by fury118** [comment]
code:

require_once 'vendor/autoload.php';
use garethp\ews\Contacts\ContactsAPI as API;
use \garethp\ews\API\Enumeration;
$api = API::withUsernameAndPassword($exchangeServeur, $exchangeUtilisateur, $exchangeMdp, ['drillDownResponses' => false]);

$contacts = $api->getContacts();
$max=$contacts->getTotalItemsInView();
echo $max;



result:
Fatal error: Uncaught Exception: Property TotalItemsInView does not exist in C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php:118 Stack trace: #0 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(54): garethp\ews\API\Type->getValidNameInCorrectCase(Array) #1 C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(28): garethp\ews\API\Type->get('TotalItemsInVie...') #2 C:\xampp\htdocs\secure\ajax\intervenantAnnuaireSync.php(63): garethp\ews\API\Type->__call('getTotalItemsIn...', Array) #3 {main} thrown in C:\xampp\htdocs\secure\ajax\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php on line 118

**Comment by Garethp** [comment]
Why are you setting `'drillDownResponses' => false`? Can you please tell me what you get when you do

```php
echo get_class($contacts);
```

Can you try removing `drillDownResponses` and letting me know if it works?

**Comment by Garethp** [comment]
I'll look in to it and see what's going on

**Comment by fury118** [comment]
I use this example

https://github.com/Garethp/php-ews/blob/master/examples/basic/pagingRequests.php

code:
$api = API::withUsernameAndPassword($exchangeServeur, $exchangeUtilisateur, $exchangeMdp);
$contacts = $api->getContacts();
echo get_class($contacts);

result:
garethp\ews\API\Type\FindItemParentType

**Comment by Garethp** [comment]
Can you try getting the next page of contacts like that, without disabling `drillDownResponses`?

**Comment by fury118** [comment]
code:

$api = API::withUsernameAndPassword($exchangeServeur, $exchangeUtilisateur, $exchangeMdp);
$firstPage = $api->getContacts(); 
print_r($firstPage[100]);
$secondPage = $api->getNextPage($firstPage); 
print_r ($secondPage[100]);

result:

i get the same contact

**Comment by Garethp** [comment]
Thanks. Yes, that's how you would get the third page. I'll look in to why this didn't work right off the bat

**Comment by Garethp** [comment]
Can you try something for me? Can you try the following an let me know what it says?

```php
$firstPage = $api->getContacts();
print_r($firstPage->isIncludesLastItemInRange());
print_r(count($firstPage));
print_r($firstPage->getTotalItemsInView());
```

**Comment by fury118** [comment]
don't hesitate

$firstPage = $api->getContacts();
print_r($firstPage->isIncludesLastItemInRange());
echo"a";
print_r(count($firstPage));
echo"b";
print_r($firstPage->getTotalItemsInView());
echo"c";

result:
a1000b1999c
-1000-1999-

**Comment by Garethp** [comment]
Sorry, could you please do that with `var_dump` instead of `print_r`?

**Comment by fury118** [comment]
bool(false) int(1000) int(1999)
