### ISSUE TITLE
how to get mail list using oAuth token?

### ISSUE THREAD

**Issue by laurelBE** [Garethp/php-ews#143]
Currntly I am using username and password with foolowing code
`
$api = MailAPI::withUsernameAndPassword('server', 'username', 'password');`

but i want it with oAuth token, how can i do it?

**Comment by Garethp** [comment]
Please take a look and read through my example of [authentication with oAuth](https://github.com/Garethp/php-ews/blob/master/examples/basic/authenticatingWithOAuth.php)

**Comment by laurelBE** [comment]
Thanks
