### ISSUE TITLE
get mime content

### ISSUE THREAD

**Issue by Geoffry304** [Garethp/php-ews#149]
Hello,

I got an error when I'm trying to include the mimecontent in my unreaded maill items.

Error is : Property is not valid for this operation.

```php
$api = \garethp\ews\MailAPI::withUsernameAndPassword($server, $username, $password);
$mail = $api->getUnreadMailItems(null, ['ItemShape' => ['IncludeMimeContent' => true]]);
echo "<pre>" . print_r($mail, true) . "</pre>";
```

Without the 'IncludeMimeContent I don't get an error.

Thank you in advance.

Kind regards,
Geoffry

**Comment by Geoffry304** [comment]
I was wrong like this it works
`
 $api = \garethp\ews\MailAPI::withUsernameAndPassword($server, $username, $password);
        $mail = $api->getUnreadMailItems();
        foreach ($mail as $m){
            
            $item = $api->getItem($m->getItemId(), ['ItemShape' => ['BaseShape' => 'AllProperties', 'IncludeMimeContent' => true]]);
}
`

**Comment by Garethp** [comment]
Thanks for the update :)
