### ISSUE TITLE
Accessing the raw message or saving a message to a file

### ISSUE THREAD

**Issue by ajbommarito** [Garethp/php-ews#15]
I'm looking for a way to get a message representation that's suitable for saving to a .eml or .msg file.  In the jamesiarmes version there is a function to return the MIME content which can then be decoded and saved into a .eml file.  Is there a way to do the same in php-ews?

Thanks for the updates to the project!  We moved to hosted exchange on o365 and found that our old codebase didn't work with the new server!  I'm glad someone has moved the project on for compatibility.

**Comment by Garethp** [comment]
Huh, I didn't even know you could do that, interesting. Just an FYI, you don't need to do `return $ret->getMimeContent()->_;`, you could do `return (string) $ret->getMimeContent();` or you could just return the object itself and cast it to a string later
