### ISSUE TITLE
GetCalendarItem - options

### ISSUE THREAD

**Issue by jbostoen** [Garethp/php-ews#154]
It would be nice if function getCalendarItem also supported an optional array, so a shallow search could be performed and only a limited amount of properties would be returned.

CalendarAPI.php
```
    public function getCalendarItem($id, $changeKey, $options = [])
    {
        return $this->getItem(['Id' => $id, 'ChangeKey' => $changeKey], $options);
    }
```

API.php
```
    public function getItem($itemId, $options = array())
    {
        if ($itemId instanceof Type\ItemIdType) {
            $itemId = $itemId->toArray();
        }

        $request = array(
            'ItemShape' => array('BaseShape' => 'AllProperties'),
            'ItemIds' => array('ItemId' => $itemId)
        );

        $request = array_replace_recursive($request, $options);
		 

        return $this->getClient()->GetItem($request);
    }
```

**Comment by Garethp** [comment]
Hey, thanks for the request. I didn't realise that I *didn't* have it already there. I've gone ahead and added `$options = []` to various methods and I'll release it this week (Just need to sort out my testing account). In the mean time, feel free to use `master` if you'd like to use the changes right away
