### ISSUE TITLE
Multiple AdditionalProperties ?

### ISSUE THREAD

**Issue by jbostoen** [Garethp/php-ews#155]
How do I form a request which uses BaseShape IdOnly, but also requesting multiple AdditionalProperties?

**Comment by jbostoen** [comment]
Am I overlooking something or is this simply not possible with this library?

**Comment by Garethp** [comment]
Sorry, but I don't actually know. If it's possible with the EWS API for Exchange, then it can be done with this library. How would you normally request multiple AditionalProperties?

**Comment by Garethp** [comment]
Here, this should work

```php
$item = $api->getItem($itemId, [
    'ItemShape' => [
        'BaseShape' => 'IdOnly',
        'AdditionalProperties' => [
            'FieldURI' => [
                ['FieldURI' => 'item:Subject'],
                ['FieldURI' => 'item:DateTimeReceived']
            ],
        ]
    ]
]);
```

You're right that it does come out as

```xml
...
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="item:Subject"/>
          <t:FieldURI FieldURI="item:DateTimeReceived"/>
        </t:AdditionalProperties>
...
```

**Comment by jbostoen** [comment]
Works, thank you for this example!

**Comment by Garethp** [comment]
No worries
