### ISSUE TITLE
Intergration with LDAP using bundle like FR3DLdapBundle

### ISSUE THREAD

**Issue by Dragnucs** [Garethp/php-ews#16]
Hello,

My application needs an integration with Active Directory and Exchange. I use the bundle [FR3DLdapBundle](https://github.com/Maks3w/FR3DLdapBundle) for authentication and I want to use this bundle to show the connected user calendar.

How can I read an LDAP user calendar?

**Comment by Garethp** [comment]
Hi Dragnucs

I can't comment on how to integrate this with that bundle, but at the moment this library requires you to pass a username and password with every request. It may be possible to make it recognize that a user is already logged in, but I'm not sure how to do that at this moment. If you're willing to test code for me I might be able to make this feature

Thanks,
Gareth

**Comment by Dragnucs** [comment]
Thank you for your response.

I am going to work on the matter anyway and give you back my solution. But, before I start, what would be the best way to accomplish this? Shall I just persist the user plain password in the DB and then erase it on user logout? Or shall I find someway to save the password on the session only?

**Comment by Garethp** [comment]
Of those two suggestions, I would recommend storing it in the session. Symfony makes that easy enough. Session storage would be much better than storing it in the db

**Comment by Dragnucs** [comment]
I found a solution, and it is extremely easy and needs no modification added to php-ews.

All what is needed to be done is to set `erase_credentials` to in security.yml under `security`. This is already the case if one is using FR3DLdapBundle.

Then to retrieve the password, a simple 
```php
unserialize($request->getSession()->get('_security_main'))->getCredentials()
```
Returns the password.

I suggest adding a setting in the config that when enabled, php-ews tries to use the logged in user login and password to authenticate with Exchange.

**Comment by Garethp** [comment]
Well, php-ews can't fetch the password the way you do because php-ews is a framework agnostic library, so it has no Symfony specific code. That being said, I am looking in to ways to see if I can use already authenticated ldap connections, but honestly it's not looking promising. I can't find much information on doing that with PHP

**Comment by Garethp** [comment]
Thanks for your investigation all the same. I'm glad you found a good solution
