### ISSUE TITLE
Uncaught exception - Fatal error

### ISSUE THREAD

**Issue by jplevene** [Garethp/php-ews#161]
Every time I do a call to EWS, I do as follows:
```
try {
	$mailId = $ews>sendMail($message, array('MessageDisposition' => 'SaveOnly'));
}
catch (Exception $exception) {
	$response['error'] = $exception->getMessage();
}
```
But the exception raised by the 401 is not getting caught.

J

**Fatal error**:  Uncaught garethp\ews\API\Exception\UnauthorizedException in /var/www/html/php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServices.php:438
Stack trace:
#0 /php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(356): garethp\ews\API\ExchangeWebServices->handleNonSuccessfulResponses(NULL, 401)
#1 /php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(57): garethp\ews\API\ExchangeWebServices->processResponse(NULL)
#2 /php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(497): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#3 /php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(66): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#4 /php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServ in **/php_functions/vendor/garethp/php-ews/src/API/ExchangeWebServices.php** on line **438**

**Comment by Garethp** [comment]
Is this still happening for you? Because I do my testing on 365 and don't run into this issue

**Comment by jplevene** [comment]
Not getting any reports from users, so I'd say no

**Comment by Garethp** [comment]
Okay, then I'm going to close this issue for now. If you have it again, comment and I'll reopen
