### ISSUE TITLE
Getting calendar items is limited to 100 entries

### ISSUE THREAD

**Issue by doonot** [Garethp/php-ews#163]
Hi

First of all thanks for this amazing library!

Today we ran into an issue. We are getting all calendar events for 1 month and noticed, that the library only returns 100 items (hardcoded). Is there any chance to make this number configurable or add a paging mechanism?

CalendarAPI.php -> getCalendarItems() -> MaxEntriesReturned: 100.

Thanks and best regards,
Patrick

**Comment by Garethp** [comment]
Hi

Sorry for the late reply, I've been on holiday for the past two weeks. You should be able to configure it as such

```php
$items = $api->getCalendarItems($start, $end, [
    'CalendarView' => [
        'MaxEntriesReturned' => 1000
    ]
]);
```

You can configure the return amount with `MaxEntriesReturned`. However, I believe EWS limits this to a maximum of 1000

**Comment by doonot** [comment]
Thank you very much @Garethp. We will change it accordingly! Cheers!
