### ISSUE TITLE
Could not find package grathp/php-ews at any version for your minimum-stability (stable)

### ISSUE THREAD

**Issue by baaskoen** [Garethp/php-ews#18]
Im using Laravel 5.2.x.

I get this error:

>   [InvalidArgumentException]                                                    
>   Could not find package grathp/php-ews at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability    

When I run composer require grathp/php-ews.

**Comment by Garethp** [comment]
garethp/php-ews Has not yet hit `1.0`, because I'm likely to still make some small changes to function calls here and there. Try adding

`"garethp/php-ews": "^0.7.*"`

to your composer.json. You can also do a `require-dev` if you want, but I wouldn't recommend requiring my `dev-master` branch

**Comment by baaskoen** [comment]
That seems to be working, thanks! Maybe handy adding that to the readme?

**Comment by Garethp** [comment]
Will do, thanks
