### ISSUE TITLE
Access other users calendar

### ISSUE THREAD

**Issue by Traxxas10** [Garethp/php-ews#183]
Hello,
I have the same problem like https://github.com/Garethp/php-ews/issues/156 (already closed), and used the code from there. Problem: the folderID is empty?

```
$api = API::withUsernameAndPassword(
    $server,$username ,$password,
    [
        'primarySmtpEmailAddress' => $email
    ]
);

$folderId = $api->getDistinguishedFolderId('calendar');

echo 'folderId: '.$folderId;
```
and now, If I say:
`$calendar = $api->getCalendar();`

I still got my own calender. How can I join the calendar of $email?

best regards

**Comment by Garethp** [comment]
`$folderId` should be an object, not a string, so trying to `echo` it might not work. What do you get when you do a `var_dump($folderId);` instead?

**Comment by Traxxas10** [comment]
I have updated to the last Version, now i got

`Call to protected method garethp\ews\API::getDistinguishedFolderId() from context`

after setting the method to public and use var_dump($folderId); I get:

object(garethp\ews\API\Type\DistinguishedFolderIdType)#27 (6) { ["id":protected]=> string(8) "calendar" ["changeKey":protected]=> NULL ["mailbox":protected]=> object(garethp\ews\API\Type\EmailAddressType)#26 (8) { ["name":protected]=> NULL ["emailAddress":protected]=> string(14) "user2@domain.com" ["routingType":protected]=> NULL ["mailboxType":protected]=> NULL ["itemId":protected]=> NULL ["_"]=> string(0) "" ["_value"]=> NULL ["_typeMap":protected]=> array(0) { } } ["_"]=> string(0) "" ["_value"]=> NULL ["_typeMap":protected]=> array(0) { } }


on 

```
$folder = $api->getFolderByDistinguishedId('calendar');

var_dump($folder);

I get:
object(garethp\ews\API\Type\CalendarFolderType)#58 (14) { ["sharingEffectiveRights":protected]=> NULL ["permissionSet":protected]=> NULL ["folderId":protected]=> object(garethp\ews\API\Type\FolderIdType)#53 (5) { ["id":protected]=> string(120) "!!REPLACEDID!!" ["changeKey":protected]=> string(40) "!!REPLACED2!!" ["_"]=> string(0) "" ["_value"]=> NULL ["_typeMap":protected]=> array(0) { } } ["parentFolderId":protected]=> NULL ["folderClass":protected]=> NULL ["displayName":protected]=> string(8) "Kalender" ["totalCount":protected]=> int(3) ["childFolderCount":protected]=> int(0) ["extendedProperty":protected]=> NULL ["managedFolderInformation":protected]=> NULL ["effectiveRights":protected]=> NULL ["_"]=> string(0) "" ["_value"]=> NULL ["_typeMap":protected]=> array(0) { } }

```

**Comment by Traxxas10** [comment]
"push :-) "
![image](https://user-images.githubusercontent.com/32871327/70063810-b0248200-15e8-11ea-8dab-ffa3868377ab.png)
here you can see the rights of the user. (just free/busy time) and thats all what I need

I hope you can give me a hint or a solution :-)

best regards

**Comment by Traxxas10** [comment]
sorry for doublepost, but I think I'm just about to finish it.

here is my new request in the "getCalendarItems" function:
```
$request = [
            'Traversal' => 'Shallow',
            'ItemShape' => [
                'BaseShape' => 'IdOnly',
				'AdditionalProperties' => [
					'FieldURI' => [
						['FieldURI' => 'calendar:Start'],
						['FieldURI' => 'calendar:End'],
						['FieldURI' => 'calendar:LegacyFreeBusyStatus']
					],
				]
			],
            'CalendarView' => [
                'MaxEntriesReturned' => 100,
                'StartDate' => $start->format('c'),
                'EndDate' => $end->format('c')
            ],
            'ParentFolderIds' => $this->getFolderId()->toArray(true)
        ];
```

but I still received the access denied message - I think on "IdOnly" BaseShape?

best regards

**Comment by Garethp** [comment]
Can you post the full exception that you're getting, as well as the `var_dump` of the `$this->getFolderId()->toArray(true)`?

**Comment by Traxxas10** [comment]
Full Error Message:

`Fatal error: Uncaught garethp\ews\API\Exception\ExchangeException: Der Zugriff wird verweigert. Überprüfen Sie die Anmeldeinformationen, und versuchen Sie es dann erneut. in /home/.sites/208/site1554/web/ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php:418 Stack trace: #0 /home/.sites/208/site1554/web/ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(380): garethp\ews\API\ExchangeWebServices::getItemsFromResponse(Object(garethp\ews\API\Message\FindItemResponseMessageType)) #1 /home/.sites/208/site1554/web/ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(388): garethp\ews\API\ExchangeWebServices::drillDownResponseLevels(Object(garethp\ews\API\Message\FindItemResponseMessageType)) #2 /home/.sites/208/site1554/web/ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(368): garethp\ews\API\ExchangeWebServices::drillDownResponseLevels(Object(garethp\ews\API\Message\FindItemResponseMessageType)) #3 /home/.sites/208/site1554/web/ews/vendor/garethp/php-ews/src/API/ExchangeWebServices/Middleware in /home/.sites/208/site1554/web/ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php on line 418`

var_dump($this->getFolderId()->toArray(true));

`array(1) { ["FolderId"]=> array(2) { ["Id"]=> string(120) "AAMkADMzMWZkMTFjLTBkYTctNGJmMC1iODg0LTExxOTk0NTM3Y2I4ZQAuAAAAAABAyAKOEDiPRpOeiSGN0VlwAQDe1gyd4vgrQ4FWtII9+se7AAAAAAEOAAA=" ["ChangeKey"]=> string(40) "AgAAABYAAADe1gyd4vgrQ4FWtwII9+se7AAAFL+WU" } }`

**Comment by Garethp** [comment]
Can you post your full code again? You're trying to get the calendar through Impersonation, right?

**Comment by Traxxas10** [comment]
Yes, through Impersonation with limited rights (just free/busy time)
`$api = API::withUsernameAndPassword(
    $server,$username ,$password,
    [
        'primarySmtpEmailAddress' => $email
    ]
); 
$folder = $api->getFolderByDistinguishedId('calendar');
$calendar = $api->getCalendar();
$calendar->setFolderId($folder->getFolderId());
$items = $calendar->getCalendarItems($startdate, $enddate);`


```
 public function getCalendarItems($start = '12:00 AM', $end = '11:59 PM', $options = array())
    {
        $start = Utilities\ensureIsDateTime($start);
        $end = Utilities\ensureIsDateTime($end);


        $request = [
            'Traversal' => 'Shallow',
            'ItemShape' => [
                'BaseShape' => 'IdOnly',
				'AdditionalProperties' => [
					'FieldURI' => [
						['FieldURI' => 'calendar:Start'],
						['FieldURI' => 'calendar:End'],
						['FieldURI' => 'calendar:LegacyFreeBusyStatus']
					],
				]
			],
            'CalendarView' => [
                'MaxEntriesReturned' => 100,
                'StartDate' => $start->format('c'),
                'EndDate' => $end->format('c')
            ],
            'ParentFolderIds' => $this->getFolderId()->toArray(true) /*array(
                'FolderId' => $this->getFolderId()->toXmlObject()
            )*/
        ];


        $request = array_replace_recursive($request, $options);

        $request = Type::buildFromArray($request);
		
        $response = $this->getClient()->FindItem($request);
        $items = $response;

        return $items;
    }
```

**Comment by Garethp** [comment]
First of all, I don't think you actually *need* the

```php
$folder = $api->getFolderByDistinguishedId('calendar');
$calendar = $api->getCalendar();
$calendar->setFolderId($folder->getFolderId());
```

It should be automatic. Secondly, if you only have permission to view the Free/Busy time, you won't be able to use `getCalendarItems`, since that actually gets you a list of calendar items, which would require more permissions. It sounds like you want to use the API for getting FreeBusy status. I've got an [example](https://github.com/Garethp/php-ews/blob/master/examples/calendar/checkingIfUsersAreFree.php) that you can take a look at. You either want to take a look at `areAvailable` or if you want a more detailed response take a look at `getAvailabilityFor` which uses the EWS [`GetUserAvailability`](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getuseravailability-operation) function if you want to take a look at all of the options available to you

**Comment by Traxxas10** [comment]
:-)
thank you very much for this hint.  I works!

```
$api = API::withUsernameAndPassword($server,$username ,$password, ['timezone' => 'W. Europe Standard Time']);
$calendar = $api->getCalendar();

$availability = $calendar->getAvailabilityFor($startdate, $enddate, [$email]);

$items = $availability->getFreeBusyResponseArray()->FreeBusyResponse->getFreeBusyView()->getCalendarEventArray()->CalendarEvent;

```
