### ISSUE TITLE
no body

### ISSUE THREAD

**Issue by derbenner** [Garethp/php-ews#185]
in ows online i set an body with text and and some, in the response the body is empty

**Comment by Garethp** [comment]
Can you show me what code you're using?

**Comment by derbenner** [comment]
$client = new Client($host, $username, $password, $version);
$client->setTimezone($timezone);

$request = new FindItemType();
$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();

// Return all event properties.
$request->ItemShape = new ItemResponseShapeType();
$request->ItemShape->BaseShape = DefaultShapeNamesType::ALL_PROPERTIES;

$folder_id = new DistinguishedFolderIdType();
$folder_id->Id = DistinguishedFolderIdNameType::CALENDAR;
$request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;

$request->CalendarView = new CalendarViewType();
$request->CalendarView->StartDate = $start_date->format('c');
$request->CalendarView->EndDate = $end_date->format('c');

$response = $client->FindItem($request);
$response_messages = $response->ResponseMessages->FindItemResponseMessage;

foreach ($response_messages as $response_message) {
	// Make sure the request succeeded.
	if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
		$code = $response_message->ResponseCode;
		$message = $response_message->MessageText;
		echo "Failed to search for events with ".$code.": ".$message."\n";
	}
	
	// Iterate over the events that were found, printing some data for each.
	$items = $response_message->RootFolder->Items->CalendarItem;

$items hold an Array with all events and every event has the part:

            [Attachments] => 
            [Body] => 
            [Categories] => jamesiarmes\PhpEws\ArrayType\ArrayOfStringsType Object

where the body part is empty even though they filled in the calendar

**Comment by Garethp** [comment]
Well, two things:

1. You're using `jamesiarmes\PhpEws`, not `garethp/php-ews`. Feel free to try out `garethp/php-ews`, the code would be much much simpler and easier to write
2. When using `FindItem`, the Calendar body will never be returned. EWS doesn't allow it, for reasons that I've written up [here](https://stackoverflow.com/questions/34426828/php-ews-why-isnt-a-calendar-events-body-a-accessible-from-an-event-just-like). What you need to do is get the Item Id from the item you want to see the body for and then fetch that item directly with `GetItem`. An example on how to do it with `garethp/php-ews` can be found [here](https://github.com/Garethp/php-ews/issues/110)
