### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by Gompali** [Garethp/php-ews#187]
Hi,

When I use PHPCompatibility to check your library should be fine with PHP 7.2, I have the following errors. Is it a no-go for it ?

FILE: /mnt/src/php-ews/tests/src/Mail/MailAPITest.php
------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------
 87 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed
    |       | in PHP 7. Found: "0x0E07"
------------------------------------------------------------------------------------------------------------------------

FILE: /mnt/src/php-ews/examples/mail/creatingAnEmailUnsent.php
------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------
 18 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed
    |       | in PHP 7. Found: "0x0E07"
------------------------------------------------------------------------------------------------------------------------

Time: 2.57 secs; Memory: 20MB

**Comment by Garethp** [comment]
It should work fine in PHP 7. My test suites run against PHP 7 and report no errors
