### ISSUE TITLE
ExchangeException construct must be an instance of ResponseMessageType, string given

### ISSUE THREAD

**Issue by garciagaston** [Garethp/php-ews#189]
Argument 1 passed to garethp\ews\API\Exception\ExchangeException::__construct() must be an instance of garethp\ews\API\Message\ResponseMessageType, string given, called in /vendor/garethp/php-ews/src/API/ExchangeWebServices.php on line 446.

composer.json: 
"garethp/php-ews": "^0.9.6",

**Comment by Garethp** [comment]
What did you try that got you this exception? Can you try `master` and see if it still has this issue?

**Comment by Garethp** [comment]
With no extra information I'm going to have to close this ticket
