### ISSUE TITLE
"This site is unavailable" when getting contact list

### ISSUE THREAD

**Issue by baaskoen** [Garethp/php-ews#19]
Apologies for asking many questions, however, I'm trying to get a list of contacts:

        $ews = API::withUsernameAndPassword(
            $this->server_address,
           "my-username",
           "my-password"
        );

        // "dd" is short for "die() & var_dump()"
        try {
            dd($ews->getContacts());
        } catch (\Exception $e) {
            dd($e->getMessage());
        }

Everything within the try block does not get called. The page just fails to load and displays: "The website is unavailable, ERR_CONNECTION_RESET."

**Comment by Garethp** [comment]
Is that the exception coming from the catch block?

**Comment by baaskoen** [comment]
The exception message is not being show. Just when I do for example:

> var_dump($e->getMessage());
> die();

The page just fails to load.

**Comment by Garethp** [comment]
What's the website URL?

**Comment by baaskoen** [comment]
I'm working locally.

**Comment by Garethp** [comment]
What's the server URL then? So that I can test and debug this?

**Comment by baaskoen** [comment]
Well I can't put my project online for now, but I did find where the error occurs:

```
     /**
     * @return Type\FolderIdType
     */
    public function getFolderId()
    {
        if (!$this->folderId) {
            // This line doesn't work:
            $this->folderId = $this->getFolderByDistinguishedId('contacts')->getFolderId();
        }

        return $this->folderId;
    }
```

**Comment by Garethp** [comment]
No, I mean, what's the URL of the Exchange Web Server that you're trying to work with? The error sounds as though the Server that you're trying to work with can't be connected to

**Comment by baaskoen** [comment]
I'm  using this server address: webmail.heplatform.nl

**Comment by Garethp** [comment]
Hm, I'm able to connect to the server address, it gives me an error of 401. Can you try running this code?

```php
$api = API::withUsernameAndPassword('webmail.heplatform.nl', 'test', 'test', [
    'timezone' => 'Central European Standard Time'
]);

$timezones = $api->getServerTimezones(array(), true);
var_dump($timezones);
```

But with your username and password?

**Comment by baaskoen** [comment]
Getting no error now! I will update you if I'm sure if everything is working. Thanks!

**Comment by Garethp** [comment]
Hm... can you dump `$this->server_address`? Maybe the address was just wrong?

**Comment by baaskoen** [comment]
The address is correct. I checked many times.

**Comment by Garethp** [comment]
Okay, well let me know if you encounter the issue again

**Comment by baaskoen** [comment]
Thanks a lot. Getting a list of contacts works as a charm!
