### ISSUE TITLE
Errno 10054

### ISSUE THREAD

**Issue by gmauriello** [Garethp/php-ews#191]
Hi,
I've been using php-ews  for a long time but yesterday when I tried to process my mails it stucked on one in particular, giving me the following error: 

```
RuntimeException: Curl error: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054 in ......\vendor\jamesiarmes\php-ntlm\src\SoapClient.php:92
Stack trace:
#0 [internal function]: jamesiarmes\PhpNtlm\SoapClient->__doRequest('<?xml version="...', 'https://mail...', 'http://schemas....', 1, 0)

#1 C:\xampp\htdocs\celablog\vendor\php-ews\php-ews\src\Client.php(1631): SoapClient->__call('GetItem', Array)
```

Only 1 mail throws this exception. I don't know if it is the mail content that causes this issue (it is only text), or something else. The mail is in the inbox folder with the other ones 
Please let me know ☺

**Comment by Garethp** [comment]
Hi.

Sorry, but I'm unable to help you on this. For one, it looks like you're using a different `php-ews` library than this. Also, this looks like an error with the OpenSSL installed on your system, not the library itself.
