### ISSUE TITLE
Accessing Shared Mail boxes does not work since version 0.9.7

### ISSUE THREAD

**Issue by reeperbahnause** [Garethp/php-ews#199]
Hi,  
I don't know the reason but I'm facing an issue with accessing shared mailboxes.
I updated to version 0.9.7. and since this update I can not fetch emails of the shared mailbox anymore.
Once I downgrade everything works fine again.

Did I miss some new configuration if I want to acces a shared mailbox?

Best regards
Phillip

**Comment by Garethp** [comment]
Sorry for the late fix, but this should now be fixed in the latest version
