### ISSUE TITLE
Issue with contacts loading since 0.9.7

### ISSUE THREAD

**Issue by PierrickMartos** [Garethp/php-ews#202]
Hello @Garethp, 

First thanks for your amazing work!

I have an issue since the release of version 0.9.7 (same issue with 0.9.8), when i want to list contacts of another account that the one used on login, using `setPrimarySmtpEmailAddress`, the `getContacts` method don't return all contacts but only a few.

On the account i do my tests, i have more than 3 700 contacts, on 0.9.6 version i can get all of them (using batch of 1000 contacts with offset), starting from 0.9.7, the method `getContacts` return **only 19 contacts** in my case.

Here is the snippet:
```php
$username = 'my@email.com';
$password = 'heremypassword';
$api = \garethp\ews\ContactsAPI::withUsernameAndPassword('outlook.office365.com', $username, $password);
$api->setPrimarySmtpEmailAddress('another@email.com');

echo count($api->getContacts(null, ['IndexedPageItemView' => ['Offset' => 0]]));
```

Thanks for your help

**Comment by Garethp** [comment]
I'll see what I can spot

**Comment by PierrickMartos** [comment]
Do you have the chance to take a look @Garethp ? I've tried the 0.9.6 version but i've found that with the downgrade we now have this issue: https://github.com/Garethp/php-ews/issues/180

I'm looking on my side but so far nothing.

**Comment by Garethp** [comment]
Could you check out the latest copy of master and see if that fixes your issue

**Comment by PierrickMartos** [comment]
It works! Thanks @Garethp !

**Comment by PierrickMartos** [comment]
When do you planned to release `0.9.9` please?

**Comment by Garethp** [comment]
Most likely within the next 6-12 hours

**Comment by PierrickMartos** [comment]
On packagist i still see 0.9.8 as last version, seems like autoupdate isn't activated ;)

**Comment by Garethp** [comment]
Thanks, it's been a while since I published a version, don't know when it broke. Should be fixed now

**Comment by PierrickMartos** [comment]
Perfect, thanks!
