### ISSUE TITLE
NTLMSoapClient - Checking for invalid XML breaks 401 responses

### ISSUE THREAD

**Issue by allforme3** [Garethp/php-ews#203]
```PHP
$this->_responseCode = $response->getStatusCode();

$responseStr = $response->getBody()->__toString();
libxml_use_internal_errors(true);
$dom = new \DOMDocument("1.0", "UTF-8");
$dom->strictErrorChecking = false;
$dom->validateOnParse = false;
$dom->recover = true;
$dom->loadXML($responseStr);
$xml = simplexml_import_dom($dom);
libxml_clear_errors();
libxml_use_internal_errors(false);

return $xml->asXML();
```

If a status of 401 is returned and the $responseStr is empty it will fail with DOMDocument::loadXML(): Empty string supplied as input in /app/vendor/garethp/php-ews/src/API/NTLMSoapClient.php:217

Previously it would parsed into an UnauthorizedException after the return, Now it gives an Error.

**Comment by Garethp** [comment]
This should be fixed in the latest version of master and will be released as version 0.9.9
