### ISSUE TITLE
How to convert legacy contact ID?

### ISSUE THREAD

**Issue by baaskoen** [Garethp/php-ews#21]
When I try the following:

```
        $api = $this->makeImpersonatedAPIRequest();

        $contactId = new ItemIdType($contact->contact_id, $contact->change_key);

        $api->updateContactItem($contactId, array(
            'GivenName' => 'Jane',
            'EmailAddress:EmailAddress1' => array (
                'EmailAddresses' => array (
                    'Entry' => array('Key' => 'EmailAddress1', '_value' => 'jane.smith@gmail.com')
                )
            )
        ));
```

I'm getting this error: 

> The EWS Id is in EwsLegacyId format which is not supported by the Exchange version specified by your request. Please use the ConvertId method to convert from EwsLegacyId to EwsId format.

How do I convert this? Also on a side note, how do you update a phone number? Thank you very much!

**Comment by Garethp** [comment]
Are you specifying a specific version when creating the API?

**Comment by baaskoen** [comment]
No, here is my API request:

```
protected function makeImpersonatedAPIRequest()
    {
        return API::withUsernameAndPassword($this->server_address, $this->server_username, $this->server_password,
            array(
                'impersonation' => Auth::user()->employee->email,
                'timezone' => 'Central European Standard Time'
            ));
    }
```

**Comment by Garethp** [comment]
Okay, it looks like the issue is that you're storing ID's that you got from EWS 2007, and my library defaults to making 2010 calls. You *could* force it to only make 2007 calls, but I wouldn't recommend that. Instead, I've added a new function for you (and released `0.7.6` that contains it) that will allow you to convert an ID. [Here](https://github.com/Garethp/php-ews/blob/master/examples/basic/convertItemIdFormat.php) is an example. I would suggest you do a once over on your whole data base (fetch, convert, update) once so that you have only 2010 ID's in your DB.

Also, on the phone number update, what have you tried and what's the error you got?

**Comment by Garethp** [comment]
Contact Phone numbers are updated in the same manner as email addresses. I've added phone number to the examples for creating and updating contacts. Give me a heads up if it doesn't work

**Comment by baaskoen** [comment]
It works like a charm!

**Comment by baaskoen** [comment]
Maybe one last request and then I'm more than satisfied. Could you maybe post an example on how to create or update a contact photo? 

This current code isn't working (https://github.com/jamesiarmes/php-ews/issues/322):

        $attachment = new EWSType_FileAttachmentType();
        $path = public_path() . '/assets/img/avatars_resized/'.$this->relation->avatar;
        $attachment->Content = file_get_contents($path);
        $attachment->Name = $this->relation->avatar;
        $attachment->ContentType = 'image/'.pathinfo($path)['extension'];
        $attachment->IsContactPhoto = true;

        $contact->Attachments = new EWSType_NonEmptyArrayOfAttachmentsType();
        $contact->Attachments->FileAttachment[] = $attachment;

        $req = new EWSType_CreateAttachmentType();

        $req->ParentItemId = $this->rContact->ItemId;
        $req->Attachments = new EWSType_NonEmptyArrayOfAttachmentsType();
        $req->Attachments->FileAttachment[] = $attachment;

        $ews->CreateAttachment($req);

**Comment by Garethp** [comment]
I'm not 100% sure myself, but I'll get around to it. Can you open a seperate Github issue as a feature request for that? That way I won't forget about it
