### ISSUE TITLE
Obtaining Mailbox and Folder Size

### ISSUE THREAD

**Issue by l0ckm4** [Garethp/php-ews#218]
Is there any method available to be able to obtain the size of a mailbox and/or the size of a folder in a mailbox?

On the technet forum someone has said it is possible using extended properties but i have no idea how to do this using this library.

```
Now, it does appear that you can get the actual folder size from EWS using extended property:

PropertyTag: 0x0e08

PropertyType: Integer

Code Snippet
<GetFolder xmlns=".../messages"
            xmlns:t=".../types">
   <FolderShape>
     <t:BaseShape>AllProperties</t:BaseShape>
     <t:AdditionalProperties>
        <t:ExtendedFieldURI PropertyTag="0x0e08" PropertyType="Integer"/>
     </t:AdditionalProperties>
   </FolderShape>
   <FolderIds>
      <t:DistinguishedFolderId Id="inbox"/>
   </FolderIds>
</GetFolder>
```
Thanks in advance

**Comment by Garethp** [comment]
When you call `getFolder` in this library, you can pass along additional options which are just merged into the request. So you could try something like this:

```php
$api->getFolder($id, [
    'AdditionalProperties' => [
        'ExtendedFieldURI' => ['PropertyTag' => '0x0e08', PropertyType => 'Integer']
    ]
]);
```

I'm not sure if that's entirely the right structure, but the idea is that the options keyed array gets transformed into the XML that you need to make the call, so by playing around with what you pass in there you can make the XML request look however you want to
