### ISSUE TITLE
Create or update contact photo (example request)

### ISSUE THREAD

**Issue by baaskoen** [Garethp/php-ews#22]
Could you make an example in the docs on how to set or update a contact photo?

Help is much appreciated!

**Comment by Garethp** [comment]
Will get around to this today or tomorrow

**Comment by baaskoen** [comment]
Do you have an idea on when this will be implemented?

**Comment by Garethp** [comment]
Sorry for the delay, I've been sick lately. [Here's](https://github.com/Garethp/php-ews/blob/master/examples/contacts/uploadContactPhoto.php) the documentation on how to do it

**Comment by Garethp** [comment]
You could also do it as just one giant array, but I dislike that. Here's how you would do that

```php

<?php

use jamesiarmes\PEWS\Contacts\ContactsAPI as API;
use jamesiarmes\PEWS\API\Type;

$api = API::withUsernameAndPassword('server', 'username', 'password');

$contact = $api->getContacts()[0];
$api->getClient()->CreateAttachment(array(
    'ParentItemId' => $contact[0]->toArray(),
    'Attachments' => array('FileAttachment' => array(
        'Name' => 'Avatar',
        'Content' => file_get_contents("./github.png"),
        'ContentType' => 'image/png',
        'IsContactPhoto' => true
    ))
));
```

But honestly, I want to be moving away from doing everything in arrays. In the future, In the next release, I'll be making an `$api->createAttachment($itemId, $attachment)` function, but I don't have an ETA on that

**Comment by baaskoen** [comment]
I hope you get better soon. Thank you very much!
