### ISSUE TITLE
The localhost page isn’t working - ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by arjunnaha** [Garethp/php-ews#23]
I've used Composer to install your library but I'm getting this error

```
The localhost page isn’t working

localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```
I'm working locally and this is the code I'm using...

```
<?php
require_once "vendor/autoload.php";
use jamesiarmes\PEWS\API\Type;
use jamesiarmes\PEWS\Mail\MailAPI;

$api = MailAPI::withUsernameAndPassword('webmail.forest.wokingham.sch.uk', 'redacted', 'redacted');
$mail = $api->getMailItems();

echo $this->server_address;
echo $mail;
```

Any ideas?

**Comment by nvanheuverzwijn** [comment]
If you are working locally, shouldn't `webmail.forest.wokingham.sch.uk` be `localhost` ?

**Comment by arjunnaha** [comment]
I don't have a local exchange server, so I'm using my companies

**Comment by Garethp** [comment]
Have you got PHP Errors turned on? If so, is there an actual exception that you get?

**Comment by arjunnaha** [comment]
Yes, I've got this in my code
`error_reporting(-1);`
But I still get the same empty response error message from Chrome.

**Comment by Garethp** [comment]
What about `ini_set('display_errors', 1);`?

**Comment by arjunnaha** [comment]
Still doesn't seem to be working with `error_reporting(-1);` and/or `ini_set('display_errors', 1);`.

**Comment by nvanheuverzwijn** [comment]
If you are using a webserver to execute your request, you might want to check the logs for any error like in `/etc/apache/error.log`, assuming you are on Linux and using apache.
To test these kind of script, what you really want to do is a simple php script with the code you need, run it in command line like `php myscript.php` and see what happens.

Most likely, your exchange server might not even have the API enabled. The error you seem to have does not seem to be a PHP error but looks like a socket error like your server does not route on the internet.

**Comment by Garethp** [comment]
Unfortunately, as mentioned, this does look like a web server error as opposed to an error with my library. Without an exception or PHP error message, it's not something I can help with
