### ISSUE TITLE
Change "busy" status for event. 

### ISSUE THREAD

**Issue by Lxxrxns** [Garethp/php-ews#257]
Hi there!

Thanks for this excellent PHP library.

Is it possible to change whether an event sets a person as "busy" in Outlook?

i.e. something like: 

```
$calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'setBusy' => false
)
```

Thanks for the help!

Kind regards,

Laurens

**Comment by Dumdidum12** [comment]
Hi Lxxrxns,

Just use like this:

```
$calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'LegacyFreeBusyStatus' => 'Free'
)
```

Which status you can use can you find here:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.legacyfreebusystatus?view=exchange-ews-api

**Comment by Lxxrxns** [comment]
Thanks a lot!
