### ISSUE TITLE
Segfault in PHP5.5 when casting a string to a string in Type.php

### ISSUE THREAD

**Issue by sbenskin** [Garethp/php-ews#26]
In API\Type.php on line 165 it segfaults due to casting a string to a string (no idea why)

PR to follow.

**Comment by sbenskin** [comment]
Sorry, I thought removing the casting would fix this, but it's still happening.

**Comment by Garethp** [comment]
Hm, thanks for that, I'll investigate in to this and try to find out why the issue is caused

**Comment by Garethp** [comment]
I'm having issues reproducing this, even with PHP 5.5.9. I've tried the following code with no issues

```php
$type = new Type();
var_dump((string) $type);

$type->_ = 'test';
var_dump((string) $type);

$type->_ = array();
var_dump((string) $type);

$type->_ = 123;
var_dump((string) $type);

$type->_ = new Type();
var_dump((string) $type);

$type->_ = $type;
var_dump((string) $type);

$type->_ = &$type;
var_dump((string) $type);
exit();
```

Can you post the code you've got that you're able to replicate with? And do you know what the value of `Type::_` would be when it segfaults?

**Comment by Garethp** [comment]
Hi, could you please see if the problem persists in `0.7.8`?

**Comment by sbenskin** [comment]
Hi Garath,

Sorry for the delay in replying.

The first test of the Types works fine, it does not segfault.

The value is "Default"

Interestingly, it passes through this function 7 times, with different values of the string ("", "Default") and they work fine.  On the 8th call it segfaults with the value set to "Default"

**Comment by sbenskin** [comment]
Good news, it seems to work fine in 0.7.8!

**Comment by Garethp** [comment]
This was a rough bug to track down, due to the way the library was handling soap headers (I was modifying the `SoapClient::__default_headers` variable, an undocumented and not-to-be-touched
