### ISSUE TITLE
NTLMSoapClient Crashing

### ISSUE THREAD

**Issue by BlazingSun** [Garethp/php-ews#30]
Since version 0.7.4 NTLMSoapClient ->__call is crashing php. Probably malformed soap request? PHP => 5.6.3. I may investigate further when i have some time left.

**Comment by Garethp** [comment]
Is there any specific error? Or is it a segmentation fault?

**Comment by BlazingSun** [comment]
Just a segfault in the c-part. If i only call $response = parent::__call($name, $args); it is working.

**Comment by Garethp** [comment]
What headers do you set?

**Comment by Garethp** [comment]
Hi, can you please test on version `0.7.8`, I think I may have fixed it

**Comment by BlazingSun** [comment]
Yes, seems to be fixed. Tested with 8.1.

**Comment by Garethp** [comment]
Thanks for pointing it out. It was plauging my travis tests too without telling me where the segfault happened, and I wasn't able to reproduce
