### ISSUE TITLE
calendar event 'body'

### ISSUE THREAD

**Issue by erickengelke** [Garethp/php-ews#33]
I can create calendar events for myself and others, but I'd like to put a message body/description in the event telling people what it's about.  I've searched through the schema but don't see how to do this.  I need to send about 5 lines of text.

Erick

**Comment by Garethp** [comment]
```php
<?php

use garethp\ews\API;

$api = API::withUsernameAndPassword('server', 'username', 'password');
$calendar = $api->getCalendar();

$start = new DateTime('8:00 AM');
$end = new DateTime('9:00 AM');

$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => 'Test',
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'Body' => array ('BodyType' => 'HTML', '_value' => 'Your HTML Text Here')
));
```

You can also set the BodyType to `Text` if you want to send text
