### ISSUE TITLE
Versioning confusion

### ISSUE THREAD

**Issue by brainformatik** [Garethp/php-ews#38]
Hi Garethp,

what is the intent to generate tags for v0.7.9 and v0.8.3? to be specific what is the difference between this two?

**Comment by Garethp** [comment]
Hey Brainformatik

In version 0.8.0, I changed the namespace of the project all together. Despite the fact that this project is still in pre-1.0.0 stage, I figured that this was too big of a change to make without providing support for old namespace for a little bit, to allow a transition.

So, for this month I'm porting all changes I make to the 0.8.x tags back in to the 0.7.x branch. That way people have a month to do their upgrade while still receiving bug fixes and some new features. On the 1st of June I'll no longer be supporting the 0.7.x releases.

Does that clear it up?

**Comment by brainformatik** [comment]
yeap, thx 👍

**Comment by brainformatik** [comment]
:
