### ISSUE TITLE
Public Calendar

### ISSUE THREAD

**Issue by teadawg** [Garethp/php-ews#41]
Hi,

could you please provide an example for the "getListOfChanges" script using a public calendar (public folder)?

**Comment by Garethp** [comment]
Hi. The first thing to do would be to get the folder ID of your public folder. You can do this through `getFolderByDistinguishedId($distinguishedId)`, if it's a distinguished folder, `getChildrenFolders($parentFolderId = 'root', $options = array())` if you've got it's parent folder or `getFolderByDisplayName($folderName, $parentFolderId = 'root', $options = array())` if  you only have a Folder Name. All of these should return a folderId. Then you set the folder ID to the calendar. So the complete example would look something like

```php
<?php

use garethp\ews\API;

$api = API::withUsernameAndPassword('server', 'username', 'password');

//Get the default calendar
$calendar = $api->getCalendar();

//Do whatever it is you need to do to get the folderId here
$folderId = $api->getFolderByDisplayName('Name', $parentFolderId);

//Get a calendar by the name 'Test'
$calendar->setFolderId($folderId);

//Get the initial list of Items
$changes = $calendar->listChanges();

//We use this to keep track of when we last asked for items
$syncState = $changes->getSyncState();

//Get a list of changes since we last asked for them
$changesSinceLsatCheck = $calendar->listChanges($syncState);
```

How you get the folder ID I'm not 100% sure on. I'm not sure what your setup is or what a "public folder" is exactly, or how to work with them

**Comment by Garethp** [comment]
On doing a little bit of research, if you go down the `getFolderByDisplayName` or `getChildrenFolders` route, you should use `'publicfoldersroot'` as the `parentFolderId`. So maybe something like this

```php
<?php

use garethp\ews\API;
use garethp\ews\API\Enumeration;

$api = API::withUsernameAndPassword('server', 'username', 'password');

//Get the default calendar
$calendar = $api->getCalendar();

//Do whatever it is you need to do to get the folderId here
$folderId = $api->getFolderByDisplayName('My Public Folder', Enumeration\DistinguishedFolderIdNameType::PUBLICFOLDERSROOT);

//Get a calendar by the name 'Test'
$calendar->setFolderId($folderId);

//Get the initial list of Items
$changes = $calendar->listChanges();

//We use this to keep track of when we last asked for items
$syncState = $changes->getSyncState();

//Get a list of changes since we last asked for them
$changesSinceLsatCheck = $calendar->listChanges($syncState);
```

**Comment by teadawg** [comment]
Hi, thanks for your help. It works getting the folder ID with your 2. example. However if I call `listChanges`, I get the following error:

`'SyncFolderItems' has an invalid child element 'SyncScope' in Namespace 'http://schemas.microsoft.com/exchange/services/2006/messages'. `

**Comment by Garethp** [comment]
That's... very odd. What version of Exchange are you running?

**Comment by teadawg** [comment]
I'm using Exchange 2007 SP3, for ews to work I had to set version to `Exchange2007_SP1`.

**Comment by Garethp** [comment]
That's probably a good idea. I'd suggest setting it to `Exchange2007_SP3` just to be safe, or upgrading to Exchange 2010 or Exchange 2013, but it's good to see that you managed to solve it

**Comment by Garethp** [comment]
Is your question answered?

**Comment by teadawg** [comment]
Sorry for not being clear. The error still appears. EWS did not work at all with `Exchange2007_SP3`, although I run SP3. Only `Exchange2007_SP1` works to get a connection. Unfortunately upgrading is no option, since the server is too old.

**Comment by Garethp** [comment]
Hm... maybe SyncScope isn't supported with 2007. Can you replace `$changes = $calendar->listChanges();` with 

```php
        $request = array(
            'ItemShape' => array('BaseShape' => 'IdOnly'),
            'SyncFolderId' => array('FolderId' => $calendar->getFolderId()->toXmlObject()),
            'MaxChangesReturned' => '10'
        );

        if ($syncState != null) {
            $request['SyncState'] = $syncState;
            $request['ItemShape']['BaseShape'] = 'AllProperties';
        }

        $request = array_replace_recursive($request, $options);

        $request = Type::buildFromArray($request);
        $changes = $this->getClient()->SyncFolderItems($request);
```

And see what happens?

**Comment by teadawg** [comment]
You were right, not requesting SyncScope works. Is it possible to change that in the API for Exchange 2007? It also would be useful to set the `MaxChangesReturned` as an argument.

**Comment by Garethp** [comment]
I'll mark it as a note, and see if I can make it in to a release some time in the next month or so. To be honest, I'm not 100% sure what would be a good way of making certain exclusions based on version.

As for the `MaxChangesReturned`, I may end up making it an argument. Or at least increasing that to 100. At the moment you can change it by doing something similar to

```php
$calendar->listChanges($syncState, [
    'MaxChangesReturned' => $number
]);
```

**Comment by teadawg** [comment]
I understand that making exclusion based on version is not easy and can cause a 'mess' in the API. However since I use Exchange 2007, it would be nice if support continues. This library is a great development of the original library.

**Comment by Garethp** [comment]
Definitely support will continue, it's just more of a case of figuring out how to handle the mess. I do intend to support Exchange 2007 going forward, it's just a case of how to do that cleanly, if you know what I mean. Could you also try this in the meantime?

```php
$calendar->listChanges($syncState, [
    'SyncScope' => null
]);
```

**Comment by Garethp** [comment]
I'll add a quick messy way of removing it for Exchange 2007 in the next release. I just have an issue open at the moment about my current dev-master that I want to get resolved before I make another release.

**Comment by teadawg** [comment]
Setting `'SyncScope' => null` works. This is a good workaround for me.

**Comment by Garethp** [comment]
Cheers. Next release I'll also have an example on getting public folder ID's since this worked for you

**Comment by teadawg** [comment]
Just a little note, `getFolderId` was missing in the example. 

```php
$folderId = $api->getFolderByDisplayName('My Public Folder', Enumeration\DistinguishedFolderIdNameType::PUBLICFOLDERSROOT)->getFolderId();
```

**Comment by Garethp** [comment]
Oh, thanks! I forgot that that function returns the whole folder as opposed to the FolderId! Will make note of that when I make the example

**Comment by Garethp** [comment]
Hi there

I've implemented a middleware pattern that I'm testing out, and it should auto-remove the `SyncScope` for you. I was wondering if you'd be able to pull down `dev-master` and give it a test, to make sure that it works as expected.

Thanks,
Gareth

**Comment by teadawg** [comment]
I've just tested version 0.9 and it worked for me. Thanks!
