### ISSUE TITLE
Updating contact notes

### ISSUE THREAD

**Issue by Daursu** [Garethp/php-ews#49]
I am trying to update the contact notes using the following syntax

```php
$api->updateContactItem($contact[0]->getItemId(), [
                        'GivenName' => $customer->first_name,
                        'Notes' => $customer->notes,
                ]);
```

and I receive the following error:
```
exception 'garethp\ews\API\Exception\ExchangeException' with message 'Property is not valid for this object type.' in /var/www/vendor/garethp/php-ews/src/API/ExchangeWebServices.php:426
```

Without passing Notes property everything works fine. Any ideas?

Forgot to mention that I am connecting to outlook.office365.com

**Comment by Daursu** [comment]
I've managed to fix it.

1) I had to replace `Notes` with `Body` like this:
```php
$api->updateContactItem($contact[0]->getItemId(), [
                        'GivenName' => $customer->first_name,
                        'Body' => $customer->notes,
                ]);
```

2) I had to set the Exchange version to VERSION_2013_SP1. The others didn't seem to work.

**Comment by Garethp** [comment]
Yeah, notes doesn't seem updatable, which is odd, but that's an issue with Exchange as far as I can see
