### ISSUE TITLE
error with composer

### ISSUE THREAD

**Issue by Geoffry304** [Garethp/php-ews#5]
[ErrorException]
ZipArchive::extractTo(C:\xampp\htdocs\devintranet\protected/vendor/compose
/8cb5d89c/Garethp-php-ews-1aeace8\Resources\recordings\jamesiarmes\PEWS\Te
t/APITest::testCreateItems.json): failed to open stream: Invalid argument

**Comment by Garethp** [comment]
Version 0.6.1 should fix the Windows incompatibility. You'll have to look up how to integrate composer autoloading with Yii 1, I'm not sure how that works. If I recall, Yii 1 predates PSR-4 and PSR-0

**Comment by Geoffry304** [comment]
Autoloading works now, but i have the next error when i try to use getCalendar

SOAP client returned status of 401

With the version of jamesiarmes I can connect with the server.

**Comment by Garethp** [comment]
A 401 error means that the credentials you sent in are being rejected by the server itself. Care to send me your code with my fork and james'?

**Comment by Garethp** [comment]
Fixed in version 0.6.2
