### ISSUE TITLE
 Shared Calendar, get / create Items

### ISSUE THREAD

**Issue by maidzen** [Garethp/php-ews#52]
Hi, i try to get and create items from a shared calender.

the Calendar(DisplayName = mako) is shared from a User to the API Connection user (All Rights)
my Code so far

```
public function getCalendar() {
		$this->connect();
		$calendar = $this->api->getCalendar();
		$folderId = $this->api->getFolderByDisplayName('MaKo', Enumeration\DistinguishedFolderIdNameType::ROOT);
		$folderId->getFolderId();
		$calendar->setFolderId($folderId);

		$start = new DateTime('8:00 AM');
		$end = new DateTime('8:00 PM');
		$items = $calendar->getCalendarItems($start, $end);
		
		return $items;
		
	}
```

i think the enumeration is wrong, i already tried PUBLICFOLDERSROOT and CALENDAR but i guess i have some logical issue here

thanks for your help

**Comment by Garethp** [comment]
Are you getting an error? Is `MaKo` a folder within a public folder, or just a public folder directly?

**Comment by maidzen** [comment]
$this->api->getFolderByDisplayName is returning false

MaKo is the DisplayName of a Calender from an User sharded to the User which connects with EWS

**Comment by Garethp** [comment]
Hm... what folders do you get when you do a `getChildrenFolders()` on `PUBLICFOLDERSROOT`?

**Comment by janmuennich** [comment]
I have the same problem with opening a shared calendar folder. I fould this solution for the original php-ews: http://stackoverflow.com/questions/24609527/php-ews-access-shared-calendars

Could you help me implementing this in your API?

**Comment by Garethp** [comment]
@janmuennich 

Can you try following my [Primary SMTP Address Example](https://github.com/Garethp/php-ews/blob/master/examples/basic/primarySmtpAddress.php). I believe it should accomplish the same thing as that SO post

**Comment by janmuennich** [comment]
Thanks for the quick reply! It works with the primarySmtpEmailAddress parameter.
