### ISSUE TITLE
Get user profile information

### ISSUE THREAD

**Issue by motion-work** [Garethp/php-ews#54]
Hi everyone,

I am looking for a way to get basic user information like profile image, email etc.
Is there any way to achieve that?

Thank you very much in advance!

**Comment by zuuk** [comment]
Hi following up on this,

also tried traversing through Contacts properties and although `$contact->getHasPicture()` returns 1 then `$contact->getPhoto()` returns nothing.

**Comment by Garethp** [comment]
Hi

Sorry for not having a comment earlier. I don't have any way of looking up user information other than going through the contacts directory.

@zuuk A lot of properties, I'm guessing photo included, don't load automatically on methods that return a list of contacts. After all, imagine if you tried to load 1,000 contacts and it also sent all of their photo data? Or getting 1,000 emails, and it loads up all of the attachments as well? EWS has a server side limitation on this.

For that reason, try getting each item individually to access those properties. So just do a `$contact = $api->getItem($contact->getItemId());` and then try to get the photo from that
