### ISSUE TITLE
Event Attendees not updated

### ISSUE THREAD

**Issue by chandrakantborse87** [Garethp/php-ews#55]
Trying to update event 
getting  

`Error: Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object has no 'Attendee' property in`

Code: 
```php
$updateItems = $calendar->updateCalendarItem($itemId, array(
			'Subject' => 'Update Event',
			'Start' => (new \DateTime('8:00 PM'))->format('c'),
			'End' => (new \DateTime('8:30 PM'))->format('c'),
			'Location' => "Test",	
			'RequiredAttendees' => $RECIPIENTSTR_ARR	
));
```

Note: if we are updating Subject, start, End , Location. then it is updation properly .

but when trying to updated "Attendees" then its giving an error.

Please help me to fix this issue.
Thanks

**Comment by Garethp** [comment]
What does `$RECIPIENTSTR_ARR` look like?

**Comment by Garethp** [comment]
Hi @chandrakantborse87 Is this issue still plaguing you?

**Comment by c4ncel** [comment]
I'm seeing a similar issue. 

I can create a meeting with required attendees 

            $requiredAttendees = array();
            foreach($users as $user) { 
                $requiredAttendees[] = array('Mailbox' => array('EmailAddress' => $user));
            }
            $request['RequiredAttendees'] = $requiredAttendees;
.
.
$createdItemIds = $calendar->createCalendarItems($request, array('SendMeetingInvitations' => $invites));

But passing an array like this with an altered list to updateCalendarItem fails with the 

Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object has no 'Attendee' property in /srv/www/htdocs/exchange/vendor/garethp/php-ews/src/API/NTLMSoapClient.php:122

But if I change the array structure to this,

$requiredAttendees[] = array('Attendee' => array('Mailbox' => array('EmailAddress' => $email)));

the update call generates no error, but the attendees are not updated.

Using this altered array structure, with Attendee defined in the create call fails with 

Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object has no 'Mailbox' property in /srv/www/htdocs/exchange/vendor/garethp/php-ews/src/API/NTLMSoapClient.php:122

**Comment by ealcantara22** [comment]
You are not handling a correct structure. Check the changes in the code below.
```
$attendees = array();
foreach($users as $user) { 
   $attendees [] = array('mailbox' => array('emailAddress' => $user));
}
$request['RequiredAttendees'] = $attendees ;
$invites = 'SendToAllAndSaveCopy';
```
regards
