### ISSUE TITLE
Retrieving attachments from forwarded message with embedded attachment

### ISSUE THREAD

**Issue by mtfi-lorenzo** [Garethp/php-ews#6]
When an e-mail with an attached (e.g. Excel file), is attached to a new e-mail (e.g. dragged into a new message), unable to extract the elements from the attached message.

I am using this code from examples page with 1 line modified (var dump).  The error log and dump are included.  The mailbox in question only has 1 e-mail in it.  

php code:
$username = 'user@company';
$password = '************';
$server = 'internalEXServer.company.com';

require_once "vendor/autoload.php";
use jamesiarmes\PEWS\API\Type;
use jamesiarmes\PEWS\Mail\MailAPI;
$api = MailAPI::withUsernameAndPassword($server, $username, $password);

$mail = $api->getMailItems();
var_dump($mail);

$mailItem = $mail[1];
//When the item is first returned from getMailItems(), it doesn't have attachment information filled out. You need to
//get that mail item again directly
$mailItem = $api->getItem($mailItem->getItemId());
//getFileAttachment() always returns an array of file attachments, or null
$fileAttachment = $mailItem->getAttachments()->getFileAttachment()[0];
//Without this the content of the attachment is not returned, so we need to do another fetch to make sure we get the
//content
$attachment = $api->getAttachment($fileAttachment->getAttachmentId());
$name = $attachment->getName();
$contentType = $attachment->getContentType();
$content = $attachment->getContent();

var_dump($content);

php_errorr log:
[20-Nov-2015 10:52:22 America/Chicago] PHP Notice:  Undefined offset: 1 in /var/www/html/php-ews2/check_phish.php on line 19
[20-Nov-2015 10:52:22 America/Chicago] PHP Fatal error:  Call to a member function getItemId() on a non-object in /var/www/html/php-ews2/check_phish.php on line 22
[20-Nov-2015 10:52:42 America/Chicago] PHP Notice:  Undefined offset: 1 in /var/www/html/php-ews2/check_phish.php on line 19
[20-Nov-2015 10:52:42 America/Chicago] PHP Fatal error:  Call to a member function getItemId() on a non-object in /var/www/html/php-ews2/check_phish.php on line 22

var_dump output:
array(1) {
  [0]=>
  object(jamesiarmes\PEWS\API\Type\MessageType)#37 (57) {
    ["sender":protected]=>
    object(jamesiarmes\PEWS\API\Type\SingleRecipientType)#44 (3) {
      ["mailbox":protected]=>
      object(jamesiarmes\PEWS\API\Type\EmailAddressType)#38 (7) {
        ["name":protected]=>
        string(14) "Lastname, Firstname"
        ["emailAddress":protected]=>
        string(85) "/O=companyname/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=FLASTNAME"
        ["routingType":protected]=>
        string(2) "EX"
        ["mailboxType":protected]=>
        string(6) "OneOff"
        ["itemId":protected]=>
        NULL
        ["_"]=>
        string(0) ""
        ["_typeMap":protected]=>
        array(0) {
        }
      }
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["toRecipients":protected]=>
    NULL
    ["ccRecipients":protected]=>
    NULL
    ["bccRecipients":protected]=>
    NULL
    ["isReadReceiptRequested":protected]=>
    bool(false)
    ["isDeliveryReceiptRequested":protected]=>
    bool(false)
    ["conversationIndex":protected]=>
    string(22) "Ñ#®èK;>ëdD®‚š=u{"
    ["conversationTopic":protected]=>
    string(72) "Subject_of_original_email"
    ["from":protected]=>
    object(jamesiarmes\PEWS\API\Type\SingleRecipientType)#16 (3) {
      ["mailbox":protected]=>
      object(jamesiarmes\PEWS\API\Type\EmailAddressType)#15 (7) {
        ["name":protected]=>
        string(14) "Lastname, Firstname"
        ["emailAddress":protected]=>
        string(85) "/O=companyname/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=FLASTNAME"
        ["routingType":protected]=>
        string(2) "EX"
        ["mailboxType":protected]=>
        string(6) "OneOff"
        ["itemId":protected]=>
        NULL
        ["_"]=>
        string(0) ""
        ["_typeMap":protected]=>
        array(0) {
        }
      }
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["internetMessageId":protected]=>
    string(60) "<365326ae4c254da3b7b2a62b4e43d6df@EXCHSERVER.companyname.com>"
    ["isRead":protected]=>
    bool(true)
    ["isResponseRequested":protected]=>
    NULL
    ["references":protected]=>
    NULL
    ["replyTo":protected]=>
    NULL
    ["receivedBy":protected]=>
    object(jamesiarmes\PEWS\API\Type\SingleRecipientType)#49 (3) {
      ["mailbox":protected]=>
      object(jamesiarmes\PEWS\API\Type\EmailAddressType)#48 (7) {
        ["name":protected]=>
        string(19) "Destination User"
        ["emailAddress":protected]=>
        NULL
        ["routingType":protected]=>
        string(2) "EX"
        ["mailboxType":protected]=>
        string(6) "OneOff"
        ["itemId":protected]=>
        NULL
        ["_"]=>
        string(0) ""
        ["_typeMap":protected]=>
        array(0) {
        }
      }
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["receivedRepresenting":protected]=>
    object(jamesiarmes\PEWS\API\Type\SingleRecipientType)#51 (3) {
      ["mailbox":protected]=>
      object(jamesiarmes\PEWS\API\Type\EmailAddressType)#52 (7) {
        ["name":protected]=>
        string(19) "Destination User"
        ["emailAddress":protected]=>
        string(85) "/O=companyname/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=DUSER444"
        ["routingType":protected]=>
        string(2) "EX"
        ["mailboxType":protected]=>
        string(6) "OneOff"
        ["itemId":protected]=>
        NULL
        ["_"]=>
        string(0) ""
        ["_typeMap":protected]=>
        array(0) {
        }
      }
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["mimeContent":protected]=>
    NULL
    ["itemId":protected]=>
    object(jamesiarmes\PEWS\API\Type\ItemIdType)#43 (4) {
      ["id":protected]=>
      string(152) "AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NABGAAAAAABp+AqPUrsDS5mJYBbgT8cMBwDr14N485PESKioLJfn3CaYAAAARQJbAACApJo0H5XLTphU22eP91LkAAApg+2/AAA="
      ["changeKey":protected]=>
      string(40) "CQAAABYAAACApJo0H5XLTphU22eP91LkAAApg9VV"
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["parentFolderId":protected]=>
    object(jamesiarmes\PEWS\API\Type\FolderIdType)#31 (4) {
      ["id":protected]=>
      string(120) "AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NAAuAAAAAABp+AqPUrsDS5mJYBbgT8cMAQDr14N485PESKioLJfn3CaYAAAARQJbAAA="
      ["changeKey":protected]=>
      string(8) "AQAAAA=="
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["itemClass":protected]=>
    string(8) "IPM.Note"
    ["subject":protected]=>
    string(72) "Subject_of_original_email"
    ["sensitivity":protected]=>
    string(6) "Normal"
    ["body":protected]=>
    NULL
    ["attachments":protected]=>
    NULL
    ["dateTimeReceived":protected]=>
    string(20) "2015-11-20T16:17:13Z"
    ["_typeMap":protected]=>
    array(5) {
      ["dateTimeReceived"]=>
      string(8) "dateTime"
      ["dateTimeSent"]=>
      string(8) "dateTime"
      ["dateTimeCreated"]=>
      string(8) "dateTime"
      ["reminderDueBy"]=>
      string(8) "dateTime"
      ["lastModifiedTime"]=>
      string(8) "dateTime"
    }
    ["size":protected]=>
    int(41006)
    ["categories":protected]=>
    NULL
    ["importance":protected]=>
    string(6) "Normal"
    ["inReplyTo":protected]=>
    NULL
    ["isSubmitted":protected]=>
    bool(false)
    ["isDraft":protected]=>
    bool(false)
    ["isFromMe":protected]=>
    bool(false)
    ["isResend":protected]=>
    bool(false)
    ["isUnmodified":protected]=>
    bool(true)
    ["internetMessageHeaders":protected]=>
    NULL
    ["dateTimeSent":protected]=>
    string(20) "2015-11-20T16:17:12Z"
    ["dateTimeCreated":protected]=>
    string(20) "2015-11-20T16:17:13Z"
    ["responseObjects":protected]=>
    NULL
    ["reminderDueBy":protected]=>
    NULL
    ["reminderIsSet":protected]=>
    bool(false)
    ["reminderMinutesBeforeStart":protected]=>
    string(1) "0"
    ["displayCc":protected]=>
    string(0) ""
    ["displayTo":protected]=>
    string(19) "Destination User"
    ["hasAttachments":protected]=>
    bool(true)
    ["extendedProperty":protected]=>
    NULL
    ["culture":protected]=>
    string(5) "en-US"
    ["effectiveRights":protected]=>
    object(jamesiarmes\PEWS\API\Type\EffectiveRightsType)#41 (9) {
      ["createAssociated":protected]=>
      bool(false)
      ["createContents":protected]=>
      bool(false)
      ["createHierarchy":protected]=>
      bool(false)
      ["delete":protected]=>
      bool(true)
      ["modify":protected]=>
      bool(true)
      ["read":protected]=>
      bool(true)
      ["viewPrivateItems":protected]=>
      NULL
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["lastModifiedName":protected]=>
    string(14) "Lastname, Firstname"
    ["lastModifiedTime":protected]=>
    string(20) "2015-11-20T16:17:13Z"
    ["isAssociated":protected]=>
    bool(false)
    ["webClientReadFormQueryString":protected]=>
    string(204) "?ItemID=AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NABGAAAAAABp%2BAqPUrsDS5mJYBbgT8cMBwDr14N485PESKioLJfn3CaYAAAARQJbAACApJo0H5XLTphU22eP91LkAAApg%2B2%2FAAA%3D&exvsurl=1&viewmodel=ReadMessageItem"
    ["webClientEditFormQueryString":protected]=>
    NULL
    ["conversationId":protected]=>
    object(jamesiarmes\PEWS\API\Type\ItemIdType)#12 (4) {
      ["id":protected]=>
      string(80) "AAQkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NAAQADs+62QDGEQRroKaDz2ddXs="
      ["changeKey":protected]=>
      NULL
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["uniqueBody":protected]=>
    NULL
    ["storeEntryId":protected]=>
    NULL
    ["_"]=>
    string(0) ""
  }
}

**Comment by Garethp** [comment]
I can see a couple of possible problems here. The first is that you're not getting the right mailItem. You say there's only 1 message in the mailbox, and you're right, the array of MailItems only has one item in the array. So `$mailItem = $mail[1];` should be `$mailItem = $mail[0];`

Secondly, there are [two kinds of attachments](https://msdn.microsoft.com/en-us/library/office/dn726693(v=exchg.150).aspx). Email attachments and File Attachments. In your original post on james' repo, you were trying to get an ItemAttachment, not a FileAttachment. Can you do a var_dump on `$mailItem->getAttachments()` ?

In order to get an ItemAttachment, you should instead do `$itemAttachment= $mailItem->getAttachments()->getItemAttachment()[0];` In a release in the next week there'll be a way to get both ItemAttachments and FileAttachments in one go, but for the moment you need to get them separately like this.

**Comment by mtfi-lorenzo** [comment]
Sorry about the rookie mistake with the mailItem.   I have corrected it and I am able to get the attachment's name and content type, but not the content itself (to save to a file).  

Here's the php file:
require_once "vendor/autoload.php";
use jamesiarmes\PEWS\API\Type;
use jamesiarmes\PEWS\Mail\MailAPI;
$api = MailAPI::withUsernameAndPassword($server, $username, $password);

$mail = $api->getMailItems();

$mailItem = $mail[0];
$mailItem = $api->getItem($mailItem->getItemId());

var_dump($mailItem->getAttachments() );

$itemAttachment= $mailItem->getAttachments()->getItemAttachment()[0];
//var_dump ($itemAttachment);

$attachment = $api->getAttachment($itemAttachment->getAttachmentId());
$name = $attachment->getName();
$contentType = $attachment->getContentType();
////The line below errors out
$content = $attachment->getContent();

echo "The name is $name, the type is $contentType\n";

here is the php_error log:
[22-Nov-2015 10:55:01 America/Chicago] PHP Fatal error:  Uncaught exception 'Exception' with message 'Property Content does not exist' in /var/www/html/php-ews2/vendor/garethp/php-ews/src/API/MagicMethodsTrait.php:59
Stack trace:
#0 /var/www/html/php-ews2/vendor/garethp/php-ews/src/API/MagicMethodsTrait.php(28): jamesiarmes\PEWS\API\Type->get('Content')
#1 /var/www/html/php-ews2/check_phish.php(34): jamesiarmes\PEWS\API\Type->__call('getContent', Array)
#2 /var/www/html/php-ews2/check_phish.php(34): jamesiarmes\PEWS\API\Type\ItemAttachmentType->getContent()
#3 {main}
  thrown in /var/www/html/php-ews2/vendor/garethp/php-ews/src/API/MagicMethodsTrait.php on line 59
[22-Nov-2015 10:55:07 America/Chicago] PHP Fatal error:  Uncaught exception 'Exception' with message 'Property Content does not exist' in /var/www/html/php-ews2/vendor/garethp/php-ews/src/API/MagicMethodsTrait.php:59
Stack trace:
#0 /var/www/html/php-ews2/vendor/garethp/php-ews/src/API/MagicMethodsTrait.php(28): jamesiarmes\PEWS\API\Type->get('Content')
#1 /var/www/html/php-ews2/check_phish.php(34): jamesiarmes\PEWS\API\Type->__call('getContent', Array)
#2 /var/www/html/php-ews2/check_phish.php(34): jamesiarmes\PEWS\API\Type\ItemAttachmentType->getContent()
#3 {main}
  thrown in /var/www/html/php-ews2/vendor/garethp/php-ews/src/API/MagicMethodsTrait.php on line 59


Here is the var_dump:

object(jamesiarmes\PEWS\API\Type\NonEmptyArrayOfAttachmentsType)#14 (4) {
  ["itemAttachment":protected]=>
  object(jamesiarmes\PEWS\API\Type\ItemAttachmentType)#7 (20) {
    ["item":protected]=>
    NULL
    ["message":protected]=>
    NULL
    ["calendarItem":protected]=>
    NULL
    ["contact":protected]=>
    NULL
    ["meetingMessage":protected]=>
    NULL
    ["meetingRequest":protected]=>
    NULL
    ["meetingResponse":protected]=>
    NULL
    ["meetingCancellation":protected]=>
    NULL
    ["task":protected]=>
    NULL
    ["postItem":protected]=>
    NULL
    ["attachmentId":protected]=>
    object(jamesiarmes\PEWS\API\Type\AttachmentIdType)#42 (5) {
      ["rootItemId":protected]=>
      NULL
      ["rootItemChangeKey":protected]=>
      NULL
      ["id":protected]=>
      string(180) "AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NABGAAAAAABp+AqPUrsDS5mJYBbgT8cMBwDr14N485PESKioLJfn3CaYAAAARQJbAACApJo0H5XLTphU22eP91LkAAApg+3lAAABEgAQAGbvRzmMKe1CvWZ7HKssY8Q="
      ["_"]=>
      string(0) ""
      ["_typeMap":protected]=>
      array(0) {
      }
    }
    ["name":protected]=>
    string(19) "Daily Report"
    ["contentType":protected]=>
    NULL
    ["contentId":protected]=>
    NULL
    ["contentLocation":protected]=>
    NULL
    ["size":protected]=>
    int(19779)
    ["lastModifiedTime":protected]=>
    string(19) "2015-11-21T18:43:05"
    ["_typeMap":protected]=>
    array(1) {
      ["lastModifiedTime"]=>
      string(8) "dateTime"
    }
    ["isInline":protected]=>
    bool(false)
    ["_"]=>
    string(0) ""
  }
  ["fileAttachment":protected]=>
  NULL
  ["_"]=>
  string(0) ""
  ["_typeMap":protected]=>
  array(0) {
  }
}

**Comment by Garethp** [comment]
Okay, so if you take a look at [`ItemAttachmentType`](https://github.com/Garethp/php-ews/blob/master/src/API/Type/ItemAttachmentType.php) class and the [Microsoft Documentation](https://msdn.microsoft.com/en-us/library/office/aa562997(v=exchg.150).aspx), you see that ItemAttachments and FileAttachments don't work in the same way.

Rather than having a content like FileAttachments, it has the Item directly. For example, if you're attaching a Mail Message (`MessageType`) to another mail, when you get your ItemAttachment you can do `$itemAttachment->getMessage()->getSubject()` to get the subject. Or if the attachment is a Calendar Item, you can do `$itemAttachment->getCalendarItem()->getStart()` to get the start time.

I'm still investigating this, and I'll probably include a feature to make it easier to get the item soon, but first I need to be able to analyze an email that has one of these ItemAttachments attached to it. For now, this should work. So it turns out that there's a good reason that `FileAttachments` and `ItemAttachments` are separated

**Comment by Garethp** [comment]
That being said, looking at [this stackoverflow answer](http://stackoverflow.com/a/12817256/1061257), there could be a way of saving the item. Maybe something like `$content = base64_encode((string) $itemAttachment->getMessage()->getMimeContent());` but I can't confirm that yet and it's untested, just a theory

**Comment by Garethp** [comment]
@mtfi-lorenzo 

Okay, so if you run on the `dev-master` branch of this library, you'll be able to save ItemAttachments now. It'll be included in the next release, but `dev-master` now includes MimeContent of ItemAttachments. So you should be able to save attachments like

```php
$attachments = $item->getAttachments();
$itemAttachment = $attachments[0]->getItemAttachment();
$itemAttachment = $api->getAttachment($itemAttachment->getAttachmentId());

$contentType = $itemAttachment()->getContentType();
$content = (string) $itemAttachment()->getItemAttachment()->getMimeContent();
```

**Comment by mtfi-lorenzo** [comment]
Garethp,  Thank you for all your assistance.  I verified I was able to get access to the attached message's attachments!  

I sincerely appreciate your time and effort.  Now I need to convert my old script from the original fork to use your fork for everything (e.g. moving messages to a folder, reply-all, etc).

Here is the final snippet that worked for me.  

$attachments = $mailItem->getAttachments();
$theItemAttachment = $attachments->getItemAttachment();

$itemAttachment = $api->getAttachment($theItemAttachment[0]->getAttachmentId());

$contentType = $itemAttachment->getContentType();
$content = base64_decode((string) $itemAttachment->getItemAttachment()->getMimeContent());

///Use https://github.com/php-mime-mail-parser/php-mime-mail-parser to extract the MIME attachments to a file(s)

**Comment by Garethp** [comment]
While I don't have a Reply-All function, you can use the [`API::moveItem()`](https://github.com/Garethp/php-ews/blob/master/src/API.php#L283) function for moving emails. If there's any other features you come across that you use constantly, let me know and I'll see what I can do to build it in.
