### ISSUE TITLE
SOAP Error: violation of encoding rules

### ISSUE THREAD

**Issue by weha** [Garethp/php-ews#62]
Hello

I've been able to set up a sync with ews without any problem but only when I browse to it.
If I set the script up via cron I get the error below.
This happens with list changes / get item ... for now
I don't know if this is my fault, it probably is, but I can't find anything about how to solve it when I search for it. (not for php-ews anyway)

List changes:
> SoapFault exception: [Client] SOAP-ERROR: Encoding: Violation of encoding rules in vendor/garethp/php-ews/src/API/NTLMSoapClient.php:122
Stack trace:
#0 vendor/garethp/php-ews/src/API/NTLMSoapClient.php(122): SoapClient->__call('SyncFolderItems', Array)
#1 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(18): garethp\ews\API\NTLMSoapClient->__call('SyncFolderItems', Array)
#2 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#3 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(32): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#4 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#5 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(48): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#6 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#7 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(55): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#8 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#9 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(66): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#10 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#11 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(508): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#12 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(298): garethp\ews\API\ExchangeWebServices->executeMiddlewareStack(Array, Object(garethp\ews\API\MiddlewareRequest))
#13 vendor/garethp/php-ews/src/API.php(447): garethp\ews\API\ExchangeWebServices->__call('SyncFolderItems', Array)
#14 vendor/garethp/php-ews/src/API.php(447): garethp\ews\API\ExchangeWebServices->SyncFolderItems(Object(garethp\ews\API\Type))
#15 vendor/garethp/php-ews/src/CalendarAPI.php(220): garethp\ews\API->listItemChanges(Object(garethp\ews\API\Type\FolderIdType), 'H4sIAAAAAAAEAGN...', Array)
#16 sync_ews_calendar.php(110): garethp\ews\CalendarAPI->listChanges('H4sIAAAAAAAEAGN...')
#17 {main}
>

Get item:
>
SoapFault exception: [Client] SOAP-ERROR: Encoding: Violation of encoding rules in vendor/garethp/php-ews/src/API/NTLMSoapClient.php:122
Stack trace:
#0 vendor/garethp/php-ews/src/API/NTLMSoapClient.php(122): SoapClient->__call('GetItem', Array)
#1 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(18): garethp\ews\API\NTLMSoapClient->__call('GetItem', Array)
#2 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#3 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(32): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#4 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#5 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(48): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#6 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#7 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(55): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#8 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#9 vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(66): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#10 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#11 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(508): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#12 vendor/garethp/php-ews/src/API/ExchangeWebServices.php(298): garethp\ews\API\ExchangeWebServices->executeMiddlewareStack(Array, Object(garethp\ews\API\MiddlewareRequest))
#13 vendor/garethp/php-ews/src/API.php(419): garethp\ews\API\ExchangeWebServices->__call('GetItem', Array)
#14 vendor/garethp/php-ews/src/API.php(419): garethp\ews\API\ExchangeWebServices->GetItem(Array)
#15 vendor/garethp/php-ews/src/CalendarAPI.php(150): garethp\ews\API->getItem(Array)
#16 sync_ews_calendar.php(203): garethp\ews\CalendarAPI->getCalendarItem('AQMkADI5NTFiYTE...', 'DwAAABYAAACHxmQ...')
#17 {main}
>

**Comment by Garethp** [comment]
Can you show me what code you're trying?

**Comment by weha** [comment]
For some reason it is working now. 
I did change some utf8 encode or decode on the output but I'm not sure what exactly fixed it because right after the changes it did not work but now it does.

Go figure... thanks for replying.

**Comment by Garethp** [comment]
Is it possible that some of the items you were fetching had some names/content that were in a different character set?

**Comment by weha** [comment]
It shouldn't be, everything should be in utf8.
I checked my code and I added utf8 decode to itemid, changekey and utf8 encode to date fields.

**Comment by Garethp** [comment]
Hm... well, I'm sorry I couldn't respond sooner. If it does come up again, please send an issue straight away and I'll try to walk you through how to grab a recording of your API calls
