### ISSUE TITLE
ExchangeWebServices::Exchange2010_SP3 constant missing

### ISSUE THREAD

**Issue by hartleypool** [Garethp/php-ews#63]
Is the missing `ExchangeWebServices::Exchange2010_SP3` constant intentional?

Using `ExchangeAutodiscover` with an Exchange 2010 SP3 server discovers correctly, but the call to `garethp\ews\API\ExchangeAutodiscover->parseServerVersion('7383807B')`, fails after  interpreting (correctly) that the majorVersion = 14 and minorVersion = 3,  because it's looking for the class constant `ExchangeWebServices::class::VERSION_2010_SP3"`, which isn't defined as a constant in `garethp\ews\API\ExchangeWebServices`.
### Error

```
exception 'ErrorException' with message 'constant(): Couldn't find constant garethp\ews\API\ExchangeWebServices::VERSION_2010_SP3' in /www/htdocs/vendor/garethp/php-ews/src/API/ExchangeAutodiscover.php:68

Stack trace:

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'constant(): Cou...', '/www/htdocs/v...', 68, Array)
#1 /www/htdocs/vendor/garethp/php-ews/src/API/ExchangeAutodiscover.php(68): constant('garethp\\ews\\API...')
#2 /www/htdocs/vendor/garethp/php-ews/src/API/ExchangeAutodiscover.php(117): garethp\ews\API\ExchangeAutodiscover->parseServerVersion('7383807B')
#3 /www/htdocs/vendor/garethp/php-ews/src/API/ExchangeAutodiscover.php(96): garethp\ews\API\ExchangeAutodiscover->getServerVersionFromResponse(Array)
#4 /www/htdocs/vendor/garethp/php-ews/src/API/ExchangeAutodiscover.php(149): garethp\ews\API\ExchangeAutodiscover->newAPI('test@excha...', 'REDACTED_PASSWORD

```
### Autodiscover response

`<?xml version="1.0" encoding="utf-8"?>
<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/responseschema/2006">
<Response xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a">
<User>
    <DisplayName>Tester Account 12</DisplayName>
    <LegacyDN>/o=Domain Exchange/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=Test Account 12779</LegacyDN>
    <AutoDiscoverSMTPAddress>tester12@exchange.domain.com</AutoDiscoverSMTPAddress>
    <DeploymentId>aad7b86e-fda6-49b3-a843-66945100def5</DeploymentId>
</User>
<Account>
    <AccountType>email</AccountType>
    <Action>settings</Action>
    <Protocol>
        <Type>EXCH</Type>
        <Server>VM546658.exchange.domain.com</Server>
        <ServerDN>/o=Domain Exchange/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=VM546658</ServerDN>
        <ServerVersion>7383807B</ServerVersion>
        <MdbDN>/o=Contoso Exchange/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=VM546658/cn=Microsoft Private MDB</MdbDN>
        <AD>VM546658.exchange.domain.com</AD>
        <ASUrl>https://VM546658.exchange.domain.com/EWS/Exchange.asmx</ASUrl>
        <EwsUrl>https://VM546658.exchange.domain.com/EWS/Exchange.asmx</EwsUrl>
        <EcpUrl>https://VM546658.exchange.domain.com/ecp/</EcpUrl>
        <EcpUrl-um>?p=customize/voicemail.aspx&amp;exsvurl=1</EcpUrl-um>
        <EcpUrl-aggr>?p=personalsettings/EmailSubscriptions.slab&amp;exsvurl=1</EcpUrl-aggr>
        <EcpUrl-mt>PersonalSettings/DeliveryReport.aspx?exsvurl=1&amp;IsOWA=&lt;IsOWA&gt;&amp;MsgID=&lt;MsgID&gt;&amp;Mbx=&lt;Mbx&gt;</EcpUrl-mt>
        <EcpUrl-ret>?p=organize/retentionpolicytags.slab&amp;exsvurl=1</EcpUrl-ret>
        <EcpUrl-sms>?p=sms/textmessaging.slab&amp;exsvurl=1</EcpUrl-sms>
        <OOFUrl>https://VM546658.exchange.domain.com/EWS/Exchange.asmx</OOFUrl>
        <UMUrl>https://VM546658.exchange.domain.com/EWS/UM2007Legacy.asmx</UMUrl>
    </Protocol>
    <Protocol>
        <Type>EXPR</Type>
        <Server>exchange.domain.com</Server>
        <SSL>On</SSL>
        <AuthPackage>Basic</AuthPackage>
        <ASUrl>https://exchange.domain.com/ews/exchange.asmx</ASUrl>
        <EwsUrl>https://exchange.domain.com/ews/exchange.asmx</EwsUrl>
        <EcpUrl>https://exchange.domain.com/ecp/</EcpUrl>
        <EcpUrl-um>?p=customize/voicemail.aspx&amp;exsvurl=1</EcpUrl-um>
        <EcpUrl-aggr>?p=personalsettings/EmailSubscriptions.slab&amp;exsvurl=1</EcpUrl-aggr>
        <EcpUrl-mt>PersonalSettings/DeliveryReport.aspx?exsvurl=1&amp;IsOWA=&lt;IsOWA&gt;&amp;MsgID=&lt;MsgID&gt;&amp;Mbx=&lt;Mbx&gt;</EcpUrl-mt>
        <EcpUrl-ret>?p=organize/retentionpolicytags.slab&amp;exsvurl=1</EcpUrl-ret>
        <EcpUrl-sms>?p=sms/textmessaging.slab&amp;exsvurl=1</EcpUrl-sms>
        <OOFUrl>https://exchange.domain.com/ews/exchange.asmx</OOFUrl>
        <UMUrl>https://exchange.domain.com/ews/UM2007Legacy.asmx</UMUrl>
        <OABUrl>https://skype.exchange.domain.com/OAB/f698d4d6-2cc7-4d69-a38e-c7c8fd7dacf4/</OABUrl>
    </Protocol>
    <Protocol>
        <Type>WEB</Type>
        <Internal>
            <OWAUrl AuthenticationMethod="Basic, Fba">https://VM546658.exchange.domain.com/owa/</OWAUrl>
            <Protocol>
                <Type>EXCH</Type>
                <ASUrl>https://VM546658.exchange.domain.com/EWS/Exchange.asmx</ASUrl>
            </Protocol>
        </Internal>
    </Protocol>
</Account>
</Response>
</Autodiscover>
`

**Comment by Garethp** [comment]
It's because that constant would be invalid. Although the server is SP3, [there is no SP3 schema](https://msdn.microsoft.com/en-us/library/office/dn741586(v=exchg.150).aspx). What this means is that the upgrade between SP2 and SP3 didn't change the Exchange Web Services API at all. Since the version corrosponds to the schema, trying to make a call for that version should result in an error, since there is no such version *for EWS*. 

I suppose it looks like I might have to either manually map SP3 to SP2, or change how the autodiscover works. Expect something soon(-ish)

**Comment by sirio3mil** [comment]
I'm getting same error but with VERSION_2007_SP3, trying to put VERSION_2007 or VERSION_2007_SP1 but retrieve an exception reporting internal error.

Any idea to fix it?

Regards

**Comment by Garethp** [comment]
@sirio3mil 

What code are you trying that doesn't work on `VERSION_2007_SP1`?

**Comment by sirio3mil** [comment]
Hi @Garethp,

    include_once '..\plugins\PhpEws\vendor\autoload.php';

    use garethp\ews\API\ExchangeAutodiscover;
    use garethp\ews\API\Exception\AutodiscoverFailed;
    use garethp\ews\API\Exception\UnauthorizedException;
    use garethp\ews\API;
    use garethp\ews\MailAPI;
    use garethp\ews\API\ExchangeWebServices;
    try {
    //     $api = ExchangeAutodiscover::getAPI('xxxxx', 'xxxxxx', 'xxxxxxx');

    $api = MailAPI::withUsernameAndPassword('xxxxxx', 'xxxxxxx', 'xxxxxxxx', [
        'version' => ExchangeWebServices::VERSION_2007_SP1
    ]);
    $mail = $api->getMailItems();
    echo "<pre>";
    print_r($mail);
    echo "</pre>";
    }
    catch (UnauthorizedException $exception) {
    	echo "UnauthorizedException " . $exception->getMessage();
    }
    catch (AutodiscoverFailed $exception) {
    	echo "AutodiscoverFailed " . $exception->getMessage();
    }
    catch (Exception $exception){
    	echo "Exception " . $exception->getMessage();
    }

Then I got this:

Exception Exchange Web Services are not currently available for this request because there are no available Client Access Services Servers in the target AD Site.

this server has accounts in exchange 2013 and exchange 2007, with exchange 2013 I dont have problems, but with old I get those errors.

Autodiscovery throw unknown VERSION_2007_SP3 :-)

Regards

**Comment by Garethp** [comment]
Regarding `VERSION_2007_SP1` not working, [it looks like a problem with your CAS server](https://social.msdn.microsoft.com/Forums/en-US/54b107e0-4a9b-4644-92a3-832e12fb1b1a/i-have-this-error-exexchange-web-services-are-not-currently-available-for-this-request-because?forum=exchangesvrdevelopment), I can't help you with that. I'll note this for the Autodiscovery however

**Comment by sirio3mil** [comment]
Thanks @Garethp I will report it to sysadmin, exchange is like a black box for me. Regards.
