### ISSUE TITLE
Error for exchange 2010 login it works for 2007

### ISSUE THREAD

**Issue by nagesh314** [Garethp/php-ews#65]
I am using old version and contact sync was working very fine but for exchange 2010 contact sync is giving error 

Fatal error: Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 401' in C:\wamp\www\exchange\php-ews-master\ExchangeWebServices.php:1221 Stack trace: #0 C:\wamp\www\exchange\php-ews-master\ExchangeWebServices.php(1064): ExchangeWebServices->processResponse(NULL) #1 C:\wamp\www\exchange\contact_sync.php(63): ExchangeWebServices->SyncFolderItems(Object(EWSType_SyncFolderItemsType)) #2 {main} thrown in C:\wamp\www\exchange\php-ews-master\ExchangeWebServices.php on line 1221

**Comment by Garethp** [comment]
Can you post your code? It looks like an authentication issue, so how you're authenticating would be important

**Comment by nagesh314** [comment]
require_once 'php-ews-master/EWS_Exception.php';
/*
require_once 'php-ews-master/EWSAutodiscover.php';
require_once 'php-ews-master/EWSType.php';
require_once 'php-ews-master/ExchangeWebServices.php';
require_once 'php-ews-master/NTLMSoapClient.php';
require_once 'php-ews-master/NTLMSoapClient/Exchange.php';
*/

//https://github.com/jamesiarmes/php-ews/issues/119
$host = "mail.answerfortsmith.com";
$username = '';
$password = '';

function __autoload($class_name)
{
    $base_path = 'php-ews-master';
    $include_file = $base_path . '/' . str_replace('_', '/', $class_name) .
'.php';
    return (file_exists($include_file) ? require_once $include_file :
false);
}


$ews = new ExchangeWebServices($host,  $username, $password);
$request = new EWSType_FindItemType();

$request->ItemShape = new EWSType_ItemResponseShapeType();
$request->ItemShape->BaseShape =
EWSType_DefaultShapeNamesType::ALL_PROPERTIES;

$request->ContactsView = new EWSType_ContactsViewType();
$request->ContactsView->InitialName = 'a';
$request->ContactsView->FinalName = 'z';

$request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$request->ParentFolderIds->DistinguishedFolderId = new
EWSType_DistinguishedFolderIdType();
$request->ParentFolderIds->DistinguishedFolderId->Id =
EWSType_DistinguishedFolderIdNameType::CONTACTS;

$request->Traversal = EWSType_ItemQueryTraversalType::SHALLOW;

$response = $ews->FindItem($request);
echo '<pre>'.print_r($response, true).'</pre>';

**Comment by nagesh314** [comment]
connection is happening using $host $username $password

autodiscover is giving error

and contact or calendar related stuff also gives error.

**Comment by Garethp** [comment]
You're posting an issue on the wrong Github. Your code looks like it belongs from [this](https://github.com/jamesiarmes/php-ews) library. If you wanted to use my library, it would look like [this](https://github.com/Garethp/php-ews/blob/master/examples/contacts/listContacts.php)

**Comment by nagesh314** [comment]
is there a way to update contact email to null or is there any way to
delete that email address

**Comment by nagesh314** [comment]
Hi,

I was trying to implement this new ews thing I dont understand how its
going to work.

in the following code this line gives error $request = new GetItemType();
what is going wrong can you suggest me.

<?php
require_once("./vendor/autoload.php");
use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request;

$ews = new Client($host, $username, $password);
//$request = $ews->getClient()->GetItemType();
$request = new GetItemType();
exit;
?>

**Comment by Garethp** [comment]
What are you even trying to do? And why are you responding to this old closed ticket, instead of creating a new one?
