### ISSUE TITLE
How to create a recurring meeting ?

### ISSUE THREAD

**Issue by c4ncel** [Garethp/php-ews#67]
Is there an API method to create a recurring meeting ?

**Comment by Garethp** [comment]
You can use the standard [create calendar item example](https://github.com/Garethp/php-ews/blob/master/examples/calendar/createItem.php) as your starting point. That's the api method to use. You'll need to use additional options to make it a recurring item, but those options can be found in the Microsoft EWS documentation. I don't have a ready example at the moment, but I'll try to create one in the next week

**Comment by c4ncel** [comment]
So this example create recurring series of 5 events every other week on a Tuesday.


$createdItemIds = $calendar->createCalendarItems(array(
    'Subject' => $subject,
    'Start' => $start->format('c'),
    'End' => $end->format('c'),
    'RequiredAttendees' => array(array('Mailbox' => array('EmailAddress' => 'a@co.com')),
                                           array('Mailbox' => array('EmailAddress' => 'b@co.com'))),
    'Recurrence' => array('WeeklyRecurrence' => array('Interval' => 2, 'DaysOfWeek' => 'Tuesday'),
                          'NumberedRecurrence' => array('StartDate' => $start->format('Y-m-d'), 'NumberOfOccurrences' => 5))

    ),
    array('SendMeetingInvitations' => 'SendToAllAndSaveCopy')
);

**Comment by Garethp** [comment]
That sounds about right, thanks. I'll add that to the examples soon
