### ISSUE TITLE
Number of items into an object "Calendar"

### ISSUE THREAD

**Issue by Capall** [Garethp/php-ews#7]
Hi !
I'm looking for a function to get the number of items returned by $calendar->getCalendarItems()
in order to do something like
(for $i=0, $i < $numberOfItems , $i = $i +1)
If it already exist, I'm sorry but I didn't find it... 
And if it's a basic of php, sorry again... I'm a beginner ^^'
Anyways, thanks for you work on php-ews ! :)

**Comment by Garethp** [comment]
No problem. Have you tried the [`count`](http://php.net/manual/en/function.count.php) function? So

```php
$items = $calendar->getCalendarItems();
$numberOfItems = count($items);
```

Though it would most likely be easier and cleaner for you to just use the [`foreach`](http://php.net/manual/en/control-structures.foreach.php), function, which is supported

```php
$items = $calendar->getCalendarItems();
foreach ($items as $item) {
}
```

If that doesn't work, let me know

**Comment by Capall** [comment]
I didn't know the count function exist, sorry. But thanks it solved my problem ! :)
I already tried with a foreach but it returns this : 
Fatal error: Uncaught exception 'Exception' with message 'Property Subject does not exist'
I'm not sure but I think it's because $calendar->getCalendarItems() return an object and not an array.

**Comment by Garethp** [comment]
No, that's not an issue at all. It's an interesting error, can you send me the whole piece of code you're using? Are you trying to access the subject through `$item->Subject` or `$item->getSubject()`?

As for the the fact that it's an object that's being returned, don't worry about that. It's a little bit advanced, but I'll explain why you can still use it as an array. You're right, it *does* return an object. More specifically it should return the [`FindItemParentType`](https://github.com/Garethp/php-ews/blob/master/src/API/Type/FindItemParentType.php) object. See, most objects you can't use `foreach` or `count` on, but this object implements the [`\Countable`](http://php.net/manual/en/class.countable.php) interface, the [`\ArrayAccess`](http://php.net/manual/en/class.arrayaccess.php) interface and the [`\IteratorAggregate`](http://php.net/manual/en/class.iteratoraggregate.php). This means you can treat the object as an array, doing things like `$item = $items[0]` or `count($items)` or even `foreach($items as $item)`

**Comment by Capall** [comment]
I feel stupid, in fact you were right I can use a foreach on $items.
Because I have done a lot of copy/paste, I didn't notice before but I wrote $items instead of $item : 

foreach ($items as $item) {
    echo '<br />Sujet de la réunion : ' . $items->getSubject();
}

And of course, it returned an error...

Sorry I raised an issue for nothing.

**Comment by Garethp** [comment]
If you have any other questions or suggestions, don't hesitate to ask. The more feedback I get, the better the library will get

**Comment by Capall** [comment]
Thank for all your work on this library !
And actually I'm looking for something else, I would like to access my colleagues' calendars in order to know their availabilities.
I tried with getFolderByDisplayName but as I don't know the ParentFolderID, it do not work.

**Comment by Garethp** [comment]
Is that a calendar you can normally see through the webmail? If not, have you looked in to Impersonation?

**Comment by Capall** [comment]
Yes I can access their calendar and create meetings via the webmail.
I tried with the Impersonation but it returned this : 
"Fatal error: Uncaught SoapFault exception: [a:ErrorImpersonateUserDenied] Le compte ne dispose pas de l'autorisation d'emprunter l'identité de l'utilisateur demandé."
It says : The account is not allowed to use the user's identity.

**Comment by Garethp** [comment]
Hm... that's a really interesting use-case. I have to admit that I don't entirely know how to deal with it, since I don't actually know how to set up that kind of a situation myself. Do you have a staging environment that you could give me access to with this kind of a set up so that I can look in to how to make it work?

**Comment by Capall** [comment]
Unfortunately no because I'm doing this for an internship and I work directly on the company's webmail, not on a VM sorry...

**Comment by Capall** [comment]
Hi again !
I found this issue : https://github.com/jamesiarmes/php-ews/issues/237
It seems that it's the same problem than me, and that a solution exists... Do you think I can do the same thing with your php-ews class ?

**Comment by Garethp** [comment]
Sorry for the delayed reply. Short answer is: Yes you can. Long answer is that although the simple access API is what I use as examples, it's mostly just a wrapper around the main API base. For example, this code

```php
$folder = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$folder->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
$folder->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
$folder->DistinguishedFolderId->Mailbox = new stdClass();
$folder->DistinguishedFolderId->Mailbox->EmailAddress = $this->calDelegate->getCalendarMailbox();

$request->SavedItemFolderId = $folder;

$response = $ews->CreateItem($request);
```

Can be roughly converted as 

```php
$folder = new Type\NonEmptyArrayOfBaseFolderIdsType();
$folder->setDistinguishedFolderId(new Type\DistinguishedFolderIdType());
$folder->setDistinguishedFolderId()->setId(Enumeration\DistinguishedFolderIdNameType::CALENDAR);
$folder->setMailbox(new Type\EmailAddressType());
$folder->getMailbox()->setEmailAddress = $this->calDelegate->getCalendarMailbox();

$calendarAPI->createCalendarItems($items, array (
    'SavedItemFolderId' => $folder->toXmlObject()
));
```

That might not work without some testing or fiddling, because I haven't got the kind of setup that you have to test against. Give it a try, let me know how it works out

**Comment by Capall** [comment]
Hello ! I'm sorry too, I wasn't here the last week ^^'
I change some details so it could work for me, but I still have an error on the 4th line : 

 <code>$folder = new API\Type\NonEmptyArrayOfBaseFolderIdsType();
$folder->setDistinguishedFolderId(new API\Type\DistinguishedFolderIdType());
$folder->setDistinguishedFolderId(API\Enumeration\DistinguishedFolderIdNameType::CALENDAR);
$folder->setMailbox(new API\Type\EmailAddressType());
$folder->getMailbox()->setEmailAddress = $this->calDelegate->getCalendarMailbox();</code>

The error is: 
Fatal error: Uncaught exception 'Exception' with message 'Property Mailbox does not exist' in C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php:76 Stack trace: #0 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php(32): jamesiarmes\PEWS\API\Type->set('Mailbox', Object(jamesiarmes\PEWS\API\Type\EmailAddressType)) #1 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\Vues\test.php(17): jamesiarmes\PEWS\API\Type->__call('setMailbox', Array) #2 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\Vues\test.php(17): jamesiarmes\PEWS\API\Type\NonEmptyArrayOfBaseFolderIdsType->setMailbox(Object(jamesiarmes\PEWS\API\Type\EmailAddressType)) #3 {main} thrown in C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\MagicMethodsTrait.php on line 76

I tried to debug it but I failed....

**Comment by Garethp** [comment]
Here, this should work better

```php
$distinguishedFolderId = new Type\DistinguishedFolderIdType();
$distinguishedFolderId->setId(Enumeration\DistinguishedFolderIdNameType::CALENDAR);
$distinguishedFolderId->setMailbox(new Type\EmailAddressType());
$distinguishedFolderId->getMailbox()->setEmailAddress('EmailAddress');

$folder = new Type\NonEmptyArrayOfBaseFolderIdsType();
$folder->setDistinguishedFolderId($distinguishedFolderId);
```

The mailbox needed to be set on the FolderId itself

**Comment by Capall** [comment]
It works ! I just have a problem with this line : 
<code>$calendar->createCalendarItems($items, array('SavedItemFolderId' => $folder->toXmlObject()));</code>
I have this error : 
 Call to a member function getPrimarySmtpMailbox() on null
I think it is due to the $items declaration, I tried to do this : 
<code>$items = new Type\CalendarItemType();</code>

**Comment by Garethp** [comment]
What line is that error coming from? And how are you instantiating the api?

**Comment by Capall** [comment]
Sorry I forget the line : vendor\garethp\php-ews\src\API.php on line 33
The code for the api : 
<code>$api = API::withUsernameAndPassword($server, $_SESSION['username'], $_SESSION['password']);</code>

**Comment by Garethp** [comment]
Can you post your whole code? You shouldn't be getting that error. That error should only popup if the SOAP Client never got set. 

For more than one line of code, you can wrap it up in 

```
    ```php
    ```
```

To format it nicely. Take a look [here](https://guides.github.com/features/mastering-markdown/)

**Comment by Capall** [comment]
```php
require '../vendor/autoload.php';
require '../Infos/Connexion.php';

use jamesiarmes\PEWS\API;
use jamesiarmes\PEWS\API\Type;
use jamesiarmes\PEWS\API\Enumeration;
use jamesiarmes\PEWS\Calendar\CalendarAPI;

$api = API::withUsernameAndPassword($server, $_SESSION['username'], $_SESSION['password']);

$calendar = new CalendarAPI();

$distinguishedFolderId = new Type\DistinguishedFolderIdType();
$distinguishedFolderId->setId(Enumeration\DistinguishedFolderIdNameType::CALENDAR);
$distinguishedFolderId->setMailbox(new Type\EmailAddressType());
$distinguishedFolderId->getMailbox()->setEmailAddress('ADUVAL@dimosoftware.com');

$folder = new Type\NonEmptyArrayOfBaseFolderIdsType();
$folder->setDistinguishedFolderId($distinguishedFolderId);

$items = new Type\CalendarItemType();

$calendar->createCalendarItems($items, array('SavedItemFolderId' => $folder->toXmlObject()));
```
Thanks I didn't dare to ask how to do that...

**Comment by Garethp** [comment]
> $calendar = new CalendarAPI();

There's your problem. I guess I need to make the constructor private at some point. To get the Calendar API, try either of the following

```php
$api = API::withUsernameAndPassword($server, $_SESSION['username'], $_SESSION['password']);
$calendar = $api->getCalendar();
```

Or just directly

```php
$calendar = CalendarAPI::withUsernameAndPassword($server, $_SESSION['username'], $_SESSION['password']);
```

**Comment by Capall** [comment]
That's working, but as <code>getCalendar()</code> returns the user's calendar, I don't understand how it is possible to have the calendar of another user with <code>getCalendarItems</code> ?

**Comment by Garethp** [comment]
`getCalendar()` only returns an instance of CalendarAPI() with the default calendar of that person selected. Originally I planned that you should be able to change which folder you're working with, but I suppose I never got around to updating it. 

You should now (with the 0.7.2 release I just tagged) be able to set the folder ID that you're working with as such

```php
$api = API::withUsernameAndPassword($server, $_SESSION['username'], $_SESSION['password']);
$calendar = $api->getCalendar();

$calendar->setFolderId($folderId);
```

**Comment by Capall** [comment]
Maybe I missed something...
Because either I wrote
```php
$folder = new Type\NonEmptyArrayOfBaseFolderIdsType();
$folder->setDistinguishedFolderId($distinguishedFolderId);
$folderId = $folder->getFolderId();
$calendar->setFolderId($folderId);
$startDay = (new \DateTime('2016-01-25'))->format(DateTime::W3C);
$endDay = (new \DateTime('2016-01-30'))->format(DateTime::W3C);
$items = $calendar->getCalendarItems($startDay, $endDay);
```
and I get my calendar.
Or I wrote 
```php
$folder = new Type\NonEmptyArrayOfBaseFolderIdsType();
$folder->setDistinguishedFolderId($distinguishedFolderId);
$calendar->setFolderId($folder);
$startDay = (new \DateTime('2016-01-25'))->format(DateTime::W3C);
$endDay = (new \DateTime('2016-01-30'))->format(DateTime::W3C);
$items = $calendar->getCalendarItems($startDay, $endDay);
```
and I get this : 
Fatal error: Uncaught SoapFault exception: [a:ErrorSchemaValidation] La demande a échoué lors de la validation du schéma : L'attribut requis de 'Id' est manquant. in C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\NTLMSoapClient.php:89 Stack trace: #0 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\NTLMSoapClient.php(89): SoapClient->__call('FindItem', Array) #1 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\NTLMSoapClient\Exchange.php(28): jamesiarmes\PEWS\API\NTLMSoapClient->__call('FindItem', Array) #2 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(253): jamesiarmes\PEWS\API\NTLMSoapClient\Exchange->__call('FindItem', Array) #3 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\Calendar\CalendarAPI.php(136): jamesiarmes\PEWS\API\ExchangeWebServices->__call('FindItem', Array) #4 C:\DIMOMAINT\Apache2.4\htdocs\Outlook in C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\NTLMSoapClient.php on line 89

**Comment by Capall** [comment]
Sorry for the reopening, I misclick...

**Comment by Garethp** [comment]
Can you try

```php
$calendar->setFolderId($distinguishedFolderId);
$startDay = (new \DateTime('2016-01-25'))->format(DateTime::W3C);
$endDay = (new \DateTime('2016-01-30'))->format(DateTime::W3C);
$items = $calendar->getCalendarItems($startDay, $endDay);
```

**Comment by Capall** [comment]
I tried and I get : 
The ID is incorrect

Fatal error: Uncaught exception 'Exception' with message 'L'ID est incorrect.' in C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\ExchangeWebServices.php:358 Stack trace: #0 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(371): jamesiarmes\PEWS\API\ExchangeWebServices->drillDownResponseLevels(Object(jamesiarmes\PEWS\API\Message\FindItemResponseMessageType)) #1 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(337): jamesiarmes\PEWS\API\ExchangeWebServices->drillDownResponseLevels(Object(jamesiarmes\PEWS\API\Message\ArrayOfResponseMessagesType)) #2 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\ExchangeWebServices.php(255): jamesiarmes\PEWS\API\ExchangeWebServices->processResponse(Object(jamesiarmes\PEWS\API\Message\FindItemResponseType)) #3 C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\Calendar\C in C:\DIMOMAINT\Apache2.4\htdocs\Outlook\Outlook_Garethp\vendor\garethp\php-ews\src\API\ExchangeWebServices.php on line 358

**Comment by Garethp** [comment]
Well... how do you know the ID is correct? What ID are you using?

**Comment by Capall** [comment]
I'm trying to access one of my coworker calendar. I supposed that the ID could be his mail or his login for his computer. But both return (returns ?) the same error.
If I look into the variable calendar after the <code>$calendar->setFolderId($distinguishedFolderId);</code> I see <code>id => (string) calendar</code>

**Comment by Capall** [comment]
I did this code : 
```php
$beforeSettingFolderId = $calendar->getFolderId();
var_dump($beforeSettingFolderId);
$calendar->setFolderId($distinguishedFolderId);
$afterSettingFolderId = $calendar->getFolderId();
var_dump($afterSettingFolderId);
```
and this is what I get : 
Before : 
> object(jamesiarmes\PEWS\API\Type\FolderIdType)#32 (4) { ["id":protected]=> string(120) "AAMkADQwZmNiMmQ0LThjNjgtNGViYy1hYWZiLWY5OGQ2NTUxZTczMwAuAAAAAACGgF9lYVduRZwtakIt7/ZsAQC1nfoKn0F+TreHzBZhVsMbAAAAaHMVAAA=" ["changeKey":protected]=> string(40) "AgAAABQAAACOCxk33X9vS6YQUeb8vJSFAABsaw==" ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } 

After : 
> object(jamesiarmes\PEWS\API\Type\DistinguishedFolderIdType)#38 (5) { ["id":protected]=> string(8) "calendar" ["changeKey":protected]=> NULL ["mailbox":protected]=> object(jamesiarmes\PEWS\API\Type\EmailAddressType)#8 (7) { ["name":protected]=> NULL ["emailAddress":protected]=> string(23) "mail@mail.com" ["routingType":protected]=> NULL ["mailboxType":protected]=> NULL ["itemId":protected]=> NULL ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } }
