### ISSUE TITLE
Support for Exchange2016 and Office365

### ISSUE THREAD

**Issue by doonot** [Garethp/php-ews#75]
Hi

We are interested in using this library but need to know if Exchange2016 and Office365 are also supported? If yes, are there any examples?

Thanks and regards,
Pat

**Comment by Garethp** [comment]
Hi doonot. This library does support Exchange2016 and Office365, and the examples are the same as for older exchange versions. This doesn't support any functions specific to those versions, but any functionality from older versions will work just the same, with the same examples
