### ISSUE TITLE
Sent items synchronization

### ISSUE THREAD

**Issue by ealcantara22** [Garethp/php-ews#76]
Hi, 

Is it possible to have the list of changes of the sent items as we can do it with the calendar using the last synchronization string?

if is possible, can you guys provide an example?

thanks in advance.

**Comment by Garethp** [comment]
Were you able to do this? I hadn't found the time to create an example. If you were able to solve it, could you please post an example so I can update the docs?

**Comment by ealcantara22** [comment]
Hi, i'm running this from a symfony command class.
$user = # from db.

$ews = new EwsConfiguration($em, $this->getContainer());
$ews->connectUser($user);
if (false == $ews->isOnline()) {
    $output->writeln("Could not connect user :: " . $user->getUFullName());
    $output->writeln("Message :: " . $ews->getMessage());

    # unexpected behavior, catch and log
    # return;
}

$itemShape = new Type\ItemResponseShapeType();
$itemShape->setBaseShape(DefaultShapeNamesType::ID_ONLY);

$distinguishFolderId = new Type\DistinguishedFolderIdType();
$distinguishFolderId->setId(Type\DistinguishedFolderIdNameType::SENT);

$folderId = new Type\TargetFolderIdType();
$folderId->setDistinguishedFolderId($distinguishFolderId);

$request = new SyncFolderItemsType();
$request->setItemShape($itemShape);
$request->setSyncFolderId($folderId);
$request->setMaxChangesReturned(500);

$request->setSyncState($user->getEwsUser()->getSyncSentItemsString());

/** @var SyncFolderItemsResponseMessageType $response */
$response = $ews->getClient()->SyncFolderItems($request);

if ($response->getResponseCode() != "NoError" || $response->getResponseClass() != "Success"){
    # unexpected behavior, cath and log
    # return;
}

/** @var SyncFolderItemsCreateOrUpdateType $created */
$created = $response->getChanges()->getCreate();

# do what you need to do
# remember to update the user sync state with the new $response->getSyncState();

# is possible to get the modified and deleted items to from $response->getChanges().

**Comment by Garethp** [comment]
Okay, thanks, I'll make a general example later. For now, you should be able to simplify your code down to

```php
$folderId = $api->getFolderByDistinguishedId(Type\DistinguishedFolderIdNameType::SENT)->getFolderId();

$changes = $api->listItemChanges($folderId, $user->getEwsUser()->getSyncSentItemsString(), [ 'MaxChangesReturned' => 500 ]);

$newSyncState = $changes->getSyncState();
$created = $changes->getChanges()->getCreate();
```

I'm not really sure why you're wrapping my class in your `EwsConfiguration` or why you're talking to the API client directly, instead of using the simpler methods.

**Comment by ealcantara22** [comment]
My EwsConfigurations is just for check that the user has everything in order before establish the connection, catch any exception and show the correct message to the user. About using the client directly you're right, I'll change it right now. Thanks..
