### ISSUE TITLE
Empty trash

### ISSUE THREAD

**Issue by djimondev** [Garethp/php-ews#77]
Hello everyone,

I'm working about reading some mails to update items in my database.
I have to delete all mails and empty trash (or delete without moving to trash)

Does someone knows how to do ? 

Many thanks

**Comment by Garethp** [comment]
For the moment you can empty your trash with the following:

```php
$api->getClient()->EmptyFolder(API\Type::buildFromArray([
    'DeleteType' => 'SoftDelete',
    'DeleteSubFolders' => false,
    'FolderIds' => [
        'FolderId' => $api->getFolderByDistinguishedId(API\Enumeration\DistinguishedFolderIdNameType::DELETEDITEMS)->getFolderId()->toArray()
    ]
]));
```

I'll be adding an easier way to do it soon

**Comment by Garethp** [comment]
`0.9.2`, when it's released, will come with a `MailAPI::emptyTrash` method
