### ISSUE TITLE
Examples working with Contact records

### ISSUE THREAD

**Issue by alasdaircr** [Garethp/php-ews#8]
Hello,

Thanks for making all the changes to the library, in particular the simple function calls.

Would you be able to provide any examples of accessing/updating contact records?

**Comment by Garethp** [comment]
There's currently no easy way to deal with contacts. I might look at doing that next. However, you can access all the original functions through the 

```php
$api->getClient();
```

Method. For example, `$api->getItem($itemId)` is literally just

```php
    public function getItem($itemId, $options = array())
    {
        if ($itemId instanceof Type\ItemIdType) {
            $itemId = $itemId->toArray();
        }

        $request = array(
            'ItemShape' => array('BaseShape' => 'AllProperties'),
            'ItemIds' => array('ItemId' => $itemId)
        );

        $request = array_replace_recursive($request, $options);

        return $this->getClient()->GetItem($request);
    }
```

`API::getClient()` is a public function, so you can perform your SOAP requests against that directly. If you pass in an array, it'll automatically be converted to XML before being sent over and you'll receive objects back. So while there's nothing built to help you access/update contacts yet, you can still do that manually.

However, if you have any specific features you'd like to see in so far as contact fetching/updating, I can look at seeing if I can build them really quickly for you

**Comment by alasdaircr** [comment]
Hello,

My main requirements are a simple API to find a contact / update it's fields / or delete it. And possibly deal with batches so efficiency is not lost.

I can make an attempt at this, but I'll certainly be slower than you I think!

**Comment by Garethp** [comment]
Hey @alasdaircr 

If you take a look at my latest commit, I'm beginning to create simple usage for contacts, but it probably won't be tagged until later this week at the earliest. However, it'll be targetting how exchange stores calendars in 2007/2010. In the latest version, [they've changed how they store](https://msdn.microsoft.com/en-us/library/office/jj190895(v=exchg.150).aspx) their contacts, and to do it that way requires new XSD files. I have them, but I need to look at the viability of upgrading to them. I believe that james, who I originally forked off of, made small modifications to the XSD's, so I need to find out what they are and how they work, as well as if there are any changes I need to make to some code generators to make sure the new XSD files don't break anything.

That being said, at the moment you can get contacts that exist in the contacts folder with the master branch. It's also really simple to do manually if you want to stick to a stable branch. You should be able to take a look in to the `ContactsAPI::getContacts()` method to see how to do it manually.

As for batch transactions, it seems there's already some support for that in my library. It looks like the way you do batch operations is by [passing multiple items to the call at once](https://msdn.microsoft.com/en-us/library/office/dn645424(v=exchg.150).aspx), which is something [you can already do](https://github.com/Garethp/php-ews/blob/master/src/API.php#L230) with my library. Though I will look in to making this easier to do.

Thanks,
Gareth

**Comment by alasdaircr** [comment]
Hi @Garethp 

This is great, thanks for going to the effort. I'd already started work on a ContactsAPI patch in a similar vein. I'll rebase and keep working on it and perhaps submit something soon.

**Comment by Garethp** [comment]
Do you mind issuing a PR against my repository, so I can pull in your changes? Also, if you let me know what other features you'd like in there, I'll try to implement them.

**Comment by alasdaircr** [comment]
Will do - not quite there yet though!

I'm also looking at how to cleanly handle Extended Properties in the 'simple' library as I'm going to need to make use of these.

**Comment by Garethp** [comment]
What specifically do you mean? When fetching the contacts through FindItem, if you set the baseshape of the property to AllProperties, you should get all the extended properties you have access to through FindItem. Any more and you'll need to do a GetItem on it directly. Unless you mean you actually want to specificy just the fields you want to get to save bandwidth and time, in which case it's something I've been meaning to address for a while, and I'm open to suggestions. Maybe a fields key in the $options variable? The field URI can be looked up using the `API::getFieldUriByName` method

**Comment by alasdaircr** [comment]
All excellent, AllProperties returns the Extended ones too.

What is the cleanest way to add Extended properties to an item either when creating or updating at the moment?

**Comment by alasdaircr** [comment]
A ```fields``` key in ```$options``` would be great too

**Comment by Garethp** [comment]
As far as I'm aware you should just be able to add them as if they weren't extended fields at all. Does this not work for you?

**Comment by alasdaircr** [comment]
I wasn't aware that was possible! I'll get back to you on that.

**Comment by alasdaircr** [comment]
in examples/mail/creatingAnEmailUnsent.php the extended properties are added using the 'advanced' methods, ie ```new Type\ExtendedPropertyType()``` & ```setExtendedFieldURI``` etc

I've created a API/Contacts::createItems() method, similar to API/Calendar::createItems(). This works fine, except if I can't get an extended property to apply using the simple library.

E.g.
```php
$items[] = array(
    'GivenName' => 'Alasdair',
    'Surname' => 'Github',
    'MyIDShouldBeExtendedProperty' => '8eh3903f939f3'
);
$api->createContactItems($items);
```

```MyIDShouldBeExtendedProperty``` is not available when I subsequently request ```getContacts()```, maybe I'm doing something wrong?

**Comment by Garethp** [comment]
Ah, that's the kind of extended property you're talking about. I'm afraid I haven't worked with them enough to know how to handle them in a clean way, sorry. Have you any suggestions?

**Comment by alasdaircr** [comment]
Not right now, let me have a further play with the library and get back to you

**Comment by Garethp** [comment]
Possibly doing it through the constructor might be a good idea?

```php
//Set the message as not a draft using extended property types
$extended = new Type\ExtendedPropertyType();
$fieldUri = new Type\ExtendedFieldURI();
$fieldUri->setPropertyTag("0x0E07");
$fieldUri->setPropertyType(\jamesiarmes\PEWS\API\Enumeration\MapiPropertyTypeType::INTEGER);
$extended->setExtendedFieldURI($fieldUri);
$extended->setValue(1);
$message->addExtendedProperty($extended);
```

Could become

```php
$message->addExtendedProperty(new ExtendedPropertyType("0x0E07", MapiPropertyTypeType::INTEGER, 1));
```

Although there appear to be many more options in the ExtendedFieldURI field, which might not lend itself to a simple constructor
