### ISSUE TITLE
Which to use

### ISSUE THREAD

**Issue by mrnnn** [Garethp/php-ews#84]
Hey Gareth,

Just wondering: now that @jamesiarmes is updating his original library again, will you continue working on this? I like how you put some tests on this, but I'd rather not start using a library that will no longer be maintained. Maybe we should instead join forces to put James' library under tests instead of forking things so everybody benefits from this?

Alternatively, do you see any issues with your latest version regarding compability with the latest versions of Exchange?

**Comment by Garethp** [comment]
I'm a little bit busy at the moment, but I'm still maintaining it. I think it's great that james is updating his library again, and we did communicate about sharing some of the features, but what he's going for and what I'm going for seem to be two different things.

For example, I'm putting a lot of focus on simple API usage, something that's not on the roadmap for James yet, at least not until he's passed version 1.0. James expressed interest in having the recordable HTTP calls for unit tests, but it's also something he's not planning on doing yet. We document in different ways, and that's fine. There are a bunch of other features and ideas that we shared, but I think for now we have two different libraries for two different reasons.

Admittedy I haven't been as active as I once was, I'm at a new job and with james active again I no longer feel a distinct need to check both of our issue ques. Likewise, I haven't been at a company that has had a need for this for over a year, so finding new features to build isn't as easy as it once was. With all of this combined, I'm still maintaining and planning on expanding this library, but I've just been less active for a month or so.

Finally, no, there shouldn't be any issue with compatibility with the latest version. I run most of my tests off of Office 365. Even if I weren't, Exchange has great backwards compatible support. Sending the right version header means that even if future versions change their schema, you can still use your existing code.

With that being said, at some point I will update my `wsdl` file to the latest version

**Comment by mrnnn** [comment]
Hey Gareth,

Thanks for clearing that out! Appreciate it a lot. I’m no domain expert in any way so I didn’t know about the backward compability there. Good news though.

Much appreciated and gives me an extra reason to go for your version given it’s more test-covered and has a nicer structure all together.

I may post the occasional pull request once I get the hang of the library and understand it better :-)

Cheers!

Marijn

ps: congrats on the new job. not having to deal with Exchange is never a bad thing I guess ;-)

On Tue, 31 Jan 2017 at 16:34 Garethp

<
mailto:Garethp <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I'm a little bit busy at the moment, but I'm still maintaining it. I think it's great that james is updating his library again, and we did communicate about sharing some of the features, but what he's going for and what I'm going for seem to be two different things.

For example, I'm putting a lot of focus on simple API usage, something that's not on the roadmap for James yet, at least not until he's passed version 1.0. James expressed interest in having the recordable HTTP calls for unit tests, but it's also something he's not planning on doing yet. We document in different ways, and that's fine. There are a bunch of other features and ideas that we shared, but I think for now we have two different libraries for two different reasons.

Admittedy I haven't been as active as I once was, I'm at a new job and with james active again I no longer feel a distinct need to check both of our issue ques. Likewise, I haven't been at a company that has had a need for this for over a year, so finding new features to build isn't as easy as it once was. With all of this combined, I'm still maintaining and planning on expanding this library, but I've just been less active for a month or so.

Finally, no, there shouldn't be any issue with compatibility with the latest version. I run most of my tests off of Office 365. Even if I weren't, Exchange has great backwards compatible support. Sending the right version header means that even if future versions change their schema, you can still use your existing code.

With that being said, at some point I will update my

wsdl

file to the latest version

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/Garethp/php-ews/issues/84#issuecomment-276396850
, or
