### ISSUE TITLE
Unique Meeting Identifier Between Accounts

### ISSUE THREAD

**Issue by ealcantara22** [Garethp/php-ews#85]
Hello. I need help in a case like this.

Let's say that the Account A send a meeting request to Account B and Account C.

Is there a property or method that those account calendars share to identify that exact meeting?

**Comment by ZaeemFarooqui** [comment]
Can you help me with this?

**Comment by ealcantara22** [comment]
> 
> 
> Can you help me with this?

@ZaeemFarooqui , sorry for the very very very late response. Did you get the answers you were looking for? if not let me know how can I help.
