### ISSUE TITLE
Exchange 2016 Support

### ISSUE THREAD

**Issue by feldmarv** [Garethp/php-ews#86]
As we can see there is an "Exchange2016" constant in the ExchangeWebservices file. Did anyone successfully test or implement Exchange 2016? We get an UnauthorizedException, not sure if its because of the Exchange version. (Exchange2010 SP2 successfully implemented)

**Comment by Garethp** [comment]
It shouldn't have anything to do with the constant, unless Exchange2016 swaps up authentication methods. Are there some specific functionalities from 2016 you need or would find useful? I'll look in to this

**Comment by feldmarv** [comment]
Many thanks for your feeedback!
We would like to implement CalenderSync with Exchange 2016. All other Exchange Version work but not 16. We are not sure if its the problem from our Exchange 16 or php-ews does not support Exchange 2016 ?

**Comment by Garethp** [comment]
Can you post the code that you're trying?

**Comment by feldmarv** [comment]
For example we try to connect Exchange 16 and get the calendar object an their items. This Method works for Exmaple on Exchange2010 SP2

`    /**

    public static $api;
    public static $calendar;
     * This auth method connects with the server and returns a $calendar object
     *
     * @param $server
     * @param $username
     * @param $password
     * @param $options
     */
    public static function auth($server, $username, $password, $options) {
        self::$api = API::withUsernameAndPassword($server, $username, $password, [
            'version' => $options['version']
        ]);

        $calendar = self::$api->getCalendar();
        $items = $calendar->getCalendarItems();


    }
`

**Comment by erickengelke** [comment]
I'm looking at garethp/php-ews v 0.9.1 which I think is the latest (from what I could find with composer), and tried setting the version to Exhange2016 but I still get errors with the 2016 server.

 // proceed now
  $api = API::withUsernameAndPassword($cal_server,$cal_userid,$cal_password,['version'=>'Exchange2016'] );
  $calendar = $api->getCalendar();

I don't see a 2016 constant in your source.

ERROR: The Client Access server version doesn't match the Mailbox server version of the resource that was being accessed. To determine the correct URL to use to access the resource, use Autodiscover with the address of the resource.

autodiscover.php also fails, and despite trying to mangle in version numbers, I cannot get it to return anything.

Erick

**Comment by Garethp** [comment]
Sorry for the late response. Version 2016 has added
