### ISSUE TITLE
Sometimes Change Key Problems on E-Mails with Attachments

### ISSUE THREAD

**Issue by cfreak** [Garethp/php-ews#88]
Hi,

we are using our library with office365 and Impersonation.

When sending E-Mails with Attachments everything is okay but on every 3-4 mail we get the Error:

> The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item., Cannot save changes made to an item to store.SaveStatus: IrresolvableConflict

This is the code we are using:
```php
if (is_array($message->getChildren()) && !empty($message->getChildren())) {
                //Create our message without sending it
                $mailId = $return = $api->sendMail($office365message, ['MessageDisposition' => 'SaveOnly']);

                //Create Attachments
                foreach ($message->getChildren() as $key => $attach) {
                    $api->getClient()->CreateAttachment([
                        'ParentItemId' => $mailId->toArray(),
                        'Attachments' => [
                            'FileAttachment' => [
                                'Name' => urldecode($attach->getFilename()),
                                'Content' => $attach->getBody()
                            ]
                        ],
                    ]);
                }

                $mailId = $api->getItem($mailId)->getItemId();

                //Send the message
                $api->getClient()->SendItem([
                    'SaveItemToFolder' => true,
                    'ItemIds' => [
                        'ItemId' => $mailId->toArray()
                    ]
                ]);
            }
```

How can we avoid that, or fix that? Is that something related to office365, the implementation or the library?

Can someone please help?

Best Regards
Max

**Comment by Garethp** [comment]
Basically it means that somehow the change key that you have becomes stale while the script is running. Something's changed the email since you last got the ID. I'm not sure how it happened, maybe you're running multiple scripts that change it at the same time, or something else is changing the message.

My suggestion would be to try and wrap each operation in a try catch block, detect this specific error in the catch and then refetch the ItemId and retry your operation
