### ISSUE TITLE
Get the ID of a calendar's item

### ISSUE THREAD

**Issue by Capall** [Garethp/php-ews#9]
Hi !
I though it could be better to open a new issue, I'm trying to get an item ID but the function getItem() doesn't return the ID, but an object containing an ID and a changekey...
What is the changekey ? And how can I have the real ID please ?

**Comment by Garethp** [comment]
You need an itemId to get use getItem() in the first place. `getItem($itemId, $options = array())` takes `Type\ItemIdType` as the first argument and returns your item as a response. If you do 

```php
$item = $api->getItem($itemId);
var_dump($item->getId());
```

You should see an object containing an Id and a ChangeKey. An "ItemId" is the combination of both of those. It's both the change key and the ID of the item. I'm not entirely sure what you need out of this

**Comment by Capall** [comment]
Yeah sorry, I said <code>getItem()</code> but it was <code>getItemId</code>...
I want to be able to store an item's ID into a database. So I want to get the ID (string) and not the ItemId (object)

**Comment by Garethp** [comment]
You can get it through `getItemId()->getId()`

**Comment by Capall** [comment]
```php
$itemID = $item->getItemId;
var_dump($itemID);
```
prints NULL
so if I try <code>getId()</code> I have an error

**Comment by Garethp** [comment]
That's so weird. How are you getting your `$item`? And what other data does it have in it if you do a `var_dump($item)`

**Comment by Capall** [comment]
I get them with <code>$items = $calendar->getCalendarItems($startDay, $endDay);</code>
and if I var_dump one of them I have : 
> object(jamesiarmes\PEWS\API\Type\CalendarItemType)#14 (84) { ["uID":protected]=> string(112) "040000008200E00074C5B7101A82E0080000000070A07D6DB459D10100000000000000001000000093D522EC3022594AB5D27A1C2341504B" ["recurrenceId":protected]=> NULL ["_typeMap":protected]=> array(6) { ["recurrenceId"]=> string(8) "dateTime" ["dateTimeStamp"]=> string(8) "dateTime" ["start"]=> string(8) "dateTime" ["end"]=> string(8) "dateTime" ["originalStart"]=> string(8) "dateTime" ["appointmentReplyTime"]=> string(8) "dateTime" } ["dateTimeStamp":protected]=> string(20) "2016-01-28T09:12:36Z" ["start":protected]=> string(20) "2016-02-01T09:00:00Z" ["end":protected]=> string(20) "2016-02-01T09:30:00Z" ["originalStart":protected]=> NULL ["isAllDayEvent":protected]=> bool(false) ["legacyFreeBusyStatus":protected]=> string(4) "Busy" ["location":protected]=> string(0) "" ["when":protected]=> NULL ["isMeeting":protected]=> bool(false) ["isCancelled":protected]=> bool(false) ["isRecurring":protected]=> bool(false) ["meetingRequestWasSent":protected]=> bool(false) ["isResponseRequested":protected]=> bool(true) ["calendarItemType":protected]=> string(6) "Single" ["myResponseType":protected]=> string(7) "Unknown" ["organizer":protected]=> object(jamesiarmes\PEWS\API\Type\SingleRecipientType)#50 (3) { ["mailbox":protected]=> object(jamesiarmes\PEWS\API\Type\EmailAddressType)#51 (7) { ["name":protected]=> string(14) "Caroline ASSAF" ["emailAddress":protected]=> NULL ["routingType":protected]=> NULL ["mailboxType":protected]=> string(6) "OneOff" ["itemId":protected]=> NULL ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["requiredAttendees":protected]=> NULL ["optionalAttendees":protected]=> NULL ["resources":protected]=> NULL ["conflictingMeetingCount":protected]=> NULL ["adjacentMeetingCount":protected]=> NULL ["conflictingMeetings":protected]=> NULL ["adjacentMeetings":protected]=> NULL ["duration":protected]=> string(5) "PT30M" ["timeZone":protected]=> string(48) "(UTC+01:00) Bruxelles, Copenhague, Madrid, Paris" ["appointmentReplyTime":protected]=> NULL ["appointmentSequenceNumber":protected]=> int(0) ["appointmentState":protected]=> int(0) ["recurrence":protected]=> NULL ["firstOccurrence":protected]=> NULL ["lastOccurrence":protected]=> NULL ["modifiedOccurrences":protected]=> NULL ["deletedOccurrences":protected]=> NULL ["meetingTimeZone":protected]=> NULL ["startTimeZone":protected]=> NULL ["endTimeZone":protected]=> NULL ["conferenceType":protected]=> int(0) ["allowNewTimeProposal":protected]=> bool(true) ["isOnlineMeeting":protected]=> NULL ["meetingWorkspaceUrl":protected]=> NULL ["netShowUrl":protected]=> string(0) "" ["mimeContent":protected]=> NULL ["itemId":protected]=> object(jamesiarmes\PEWS\API\Type\ItemIdType)#15 (4) { ["id":protected]=> string(152) "AAMkADQwZmNiMmQ0LThjNjgtNGViYy1hYWZiLWY5OGQ2NTUxZTczMwBGAAAAAACGgF9lYVduRZwtakIt7/ZsBwC1nfoKn0F+TreHzBZhVsMbAAAAaHMVAACyvsZTjc0OTr3Q6AisJ0RuAAsThQQrAAA=" ["changeKey":protected]=> string(40) "DwAAABQAAACOCxk33X9vS6YQUeb8vJSFAACFaQ==" ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["parentFolderId":protected]=> object(jamesiarmes\PEWS\API\Type\FolderIdType)#17 (4) { ["id":protected]=> string(120) "AAMkADQwZmNiMmQ0LThjNjgtNGViYy1hYWZiLWY5OGQ2NTUxZTczMwAuAAAAAACGgF9lYVduRZwtakIt7/ZsAQC1nfoKn0F+TreHzBZhVsMbAAAAaHMVAAA=" ["changeKey":protected]=> string(8) "AQAAAA==" ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["itemClass":protected]=> string(15) "IPM.Appointment" ["subject":protected]=> string(18) "pon pon pata pon !" ["sensitivity":protected]=> string(6) "Normal" ["body":protected]=> NULL ["attachments":protected]=> NULL ["dateTimeReceived":protected]=> string(20) "2016-01-28T09:12:43Z" ["size":protected]=> int(5309) ["categories":protected]=> NULL ["importance":protected]=> string(6) "Normal" ["inReplyTo":protected]=> NULL ["isSubmitted":protected]=> bool(false) ["isDraft":protected]=> bool(false) ["isFromMe":protected]=> bool(false) ["isResend":protected]=> bool(false) ["isUnmodified":protected]=> bool(false) ["internetMessageHeaders":protected]=> NULL ["dateTimeSent":protected]=> string(20) "2016-01-28T09:12:43Z" ["dateTimeCreated":protected]=> string(20) "2016-01-28T09:12:36Z" ["responseObjects":protected]=> NULL ["reminderDueBy":protected]=> string(20) "2016-02-01T09:00:00Z" ["reminderIsSet":protected]=> bool(true) ["reminderMinutesBeforeStart":protected]=> string(2) "15" ["displayCc":protected]=> string(0) "" ["displayTo":protected]=> string(14) "Caroline ASSAF" ["hasAttachments":protected]=> bool(false) ["extendedProperty":protected]=> NULL ["culture":protected]=> string(5) "fr-FR" ["effectiveRights":protected]=> object(jamesiarmes\PEWS\API\Type\EffectiveRightsType)#46 (9) { ["createAssociated":protected]=> bool(false) ["createContents":protected]=> bool(false) ["createHierarchy":protected]=> bool(false) ["delete":protected]=> bool(true) ["modify":protected]=> bool(true) ["read":protected]=> bool(true) ["viewPrivateItems":protected]=> NULL ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["lastModifiedName":protected]=> string(23) "mymail@mail.com" ["lastModifiedTime":protected]=> string(20) "2016-01-28T09:12:36Z" ["isAssociated":protected]=> bool(false) ["webClientReadFormQueryString":protected]=> string(140) "?ae=Item&t=IPM.Appointment&id=RgAAAACGgF9lYVduRZwtakIt7%2fZsBwC1nfoKn0F%2bTreHzBZhVsMbAAAAaHMVAACyvsZTjc0OTr3Q6AisJ0RuAAsThQQrAAAP&exvsurl=1" ["webClientEditFormQueryString":protected]=> string(147) "?ae=Item&a=Open&t=IPM.Appointment&id=RgAAAACGgF9lYVduRZwtakIt7%2fZsBwC1nfoKn0F%2bTreHzBZhVsMbAAAAaHMVAACyvsZTjc0OTr3Q6AisJ0RuAAsThQQrAAAP&exvsurl=1" ["conversationId":protected]=> object(jamesiarmes\PEWS\API\Type\ItemIdType)#49 (4) { ["id":protected]=> string(80) "AAQkADQwZmNiMmQ0LThjNjgtNGViYy1hYWZiLWY5OGQ2NTUxZTczMwAQAKF+0ivG409Spj27or148og=" ["changeKey":protected]=> NULL ["_"]=> string(0) "" ["_typeMap":protected]=> array(0) { } } ["uniqueBody":protected]=> NULL ["storeEntryId":protected]=> NULL ["_"]=> string(0) "" }

**Comment by Garethp** [comment]
I have absolutely no idea how you can get a CalendarItem a null ItemId. That makes no sense to me

**Comment by Garethp** [comment]
Did you get any more information on this? Were you able to resolve it?

**Comment by Capall** [comment]
Well no, I stopped working on it two weeks ago with the end of my internship.
Neither me or my collegues understood how get the ID...

**Comment by Garethp** [comment]
In that case I'm going to have to close the ticket, sorry. I've been unable to reproduce this issue and without someone else being able to do it, I can't look in to it more. I wish I could help solve the issue, but without more information...

**Comment by pjwj** [comment]
If that
```
$itemID = $item->getItemId;
var_dump($itemID);
```
is really the code you were using, you missed braces for function call.
Not trying to be rude, but that's the only error I could see.
Btw, also working with php-ews during my internship. ;)

**Comment by Garethp** [comment]
@pjwj That could be it. The `var_dump` appears to show a null itemId property any way, so it might not work. Unfortunately unless @Capall can ask an ex-coworker to try it, we may never know.
