### ISSUE TITLE
Main differences from jamesiarmes/php-ews and this project

### ISSUE THREAD

**Issue by pribeirojtm** [Garethp/php-ews#92]
Can you please sumarize the difference betweeen these 2 projects since this project was forked from jamesiarmes/php-ews. Thanks

**Comment by Garethp** [comment]
James' library was overly verbose and difficult to use. I tried to make one simpler. With testing. There's many, many, many differences at this point, but that's the summary

**Comment by pribeirojtm** [comment]
@Garethp , in terms of Exchange Support and its versions what versions this project support?
Thanks

**Comment by Garethp** [comment]
This library supports Exchange 2013 at the moment. What this means is that you can use features introduced up to that version, or up to the version you're on if you're on a lower version. It all depends on what version you target. There's an option when you instantiate the API to specify the version you want to use. So if you specify `VERSION_2007`, then any code you write will work for all versions 2007 and up. If you specify 2010, it'll work for all versions 2010 and up. Exchange is completely backwards compatible. You just can't use 2010 versions on 2007.

So at the moment I support 2013 (I test against Exchange Online myself), but you can use it for any and every exchange version you want. You just can't use the newest exchange features (if there are any newer features in EWS)
