### ISSUE TITLE
How should i check if the user credentials i provided is authenticated properly with Exchange Server?

### ISSUE THREAD

**Issue by vaditya92** [Garethp/php-ews#96]
Is there any way to check the provided user credentials is an authentic one? I tried the listItems example used but it returned an error asking to provide pagination parameter. So first i want to check if im being authenticated or not.Also how to provide pagination as parameter while reading emails from exchange server?

**Comment by ealcantara22** [comment]
Hi, @vaditya92. 

In order to check the user credentials, what I do is a request like this.

```
$api = API::withUsernameAndPassword('server','username', 'password'); 
try{
 
 $api->getServerTimezones(array('Eastern Standard Time'), true);

}catch (Exception $e) {
            if ( $e instanceof UnauthorizedException || $e->getCode() == 401) {
               /* invalid credentials */
            } else {
                /* something else happened */
            }
            return false;
 }
```
Hope this help. 
Regards,
